app/controllers/auth/registrations_controller.rb, app/controllers/auth/sessions_controller.rb, app/controllers/dashboard_controller.rb, app/models/user.rb, app/views/dashboard/index.html.slim, app/views/devise/registrations/new.html.slim, app/views/devise/sessions/new.html.erb, app/views/shared/_header.html.slim, db/migrate/20161220105419_create_users.rb, db/schema.rb
Use email for login and remove name from schema and migration.
=> Fix devise usage

.rubocop.yml, app/models/minion.rb, app/models/salt_event.rb, app/models/salt_handler/minion_start.rb, db/migrate/20170123134413_create_salt_event_tables.rb, db/migrate/20170124104033_add_columns_to_salt_events.rb, db/migrate/20170124141701_add_uniq_index_on_minions_id.rb, db/schema.rb, kubernetes/manifest-templates/pharos.yaml, kubernetes/salt/config/master.d/salt-master.conf, lib/tasks/salt.rake, spec/factories/salt_event_factory.rb, spec/models/minion_spec.rb, spec/models/salt_event_spec.rb, spec/models/salt_handler/minion_start_spec.rb
Handle "minion-start" events and write a new Minion in the database when needed.
=> Handle new minion events

README.md, db/seeds.rb, kubernetes/cleanup, kubernetes/manifest-templates/salt.yaml, kubernetes/salt/config/master.d/peer.conf, kubernetes/salt/config/minion.d-ca/minion.conf, kubernetes/salt/config/minion.d-ca/signing_policies.conf, kubernetes/salt/config/minion.d/minion.conf, kubernetes/salt/grains/ca, kubernetes/setup-environment, kubernetes/start
Improve development environment by creating a certificate authority,
salt-master with correct configuration for certificates to be remotely
signed and improve the start script to set up everything needed for the
development environment.
=> Allow to point to a specific salt dir

docs/software-stack.md
=> docs: added software stack document

app/controllers/nodes_controller.rb, app/models/minion.rb, lib/pharos/salt_minion.rb, spec/controllers/nodes_controller_spec.rb
These are fixes based on the comments by @mssola [here](https://github.com/SUSE/pharos/pull/15). I mistakenly closed the PR before he submitted his comments.
=> Small fixes based on (accidentally) closed Pull Request comments

README.md
=> Updated links from Travis and Code climate

Gemfile, Gemfile.lock
we are not so tied anymore to what we have in SLE12, so we can
bump the version up again
=> Gemfile: bump mysql to latest version

.travis.yml
=> ci: set the proper token for code climate

packaging/suse/concourse/buildresult.sh
=> packaging: followup to exit with 1 when build failed

.codeclimate.yml
=> add codeclimate.yml

packaging/suse/concourse/buildresult.sh
=> packaging: fix error in order of execution

README.md
=> Added development documentation

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/dashboard.js, app/models/minion.rb, app/views/dashboard/_polling.html.erb, app/views/dashboard/_polling.html.slim, app/views/dashboard/index.html.slim, app/views/layouts/application.html.slim, app/views/setup/_polling.html.slim, app/views/setup/discovery.html.slim, spec/features/auth/logout_feature_spec.rb, spec/features/bootstrap_cluster_feature_spec.rb, spec/features/monitoring_feature_spec.rb, spec/spec_helper.rb, spec/support/capybara.rb, spec/views/dashboard/index.html.slim_spec.rb, spec/views/setup/discovery.html.slim_spec.rb
Re-enable polling. Also:
- Remove "highstate" column since it is redundant with status column in place
- Use a different icon in status column for every state
=> Fix minion polling

app/views/setup/discovery.html.slim
"workers" is the term we decided to use for salt minions.
=> Change "nodes" to "workers"

app/views/setup/welcome.html.slim
=> provide hints about the initial configuration

app/controllers/dashboard_controller.rb, app/views/dashboard/index.html.slim, app/views/dashboard/kubeconfig.erb, config/routes.rb, lib/velum/kubernetes.rb, lib/velum/salt.rb, spec/controllers/dashboard_controller_spec.rb, spec/factories/minions_factory.rb, spec/vcr_cassettes/kubeconfig/cluster_not_ready.yml, spec/vcr_cassettes/kubeconfig/cluster_ready.yml
Provide a download option for the kubeconfig file.
=> Provide kubectl configuration

app/views/devise/registrations/new.html.slim, app/views/devise/sessions/new.html.slim
It's Container as a Service Platform, as also shown a few lines down
in these files.
=> Typo fixes

Gemfile, config/environments/production.rb, kubernetes/manifest-templates/velum.yaml
It contained several things from the Rails 5 -> 4 transition.
=> Fixed the production environment

app/controllers/setup_controller.rb, spec/controllers/setup_controller_spec.rb
=> setup: don't allow empty initial configuration

kubernetes/manifest-templates/velum.yaml
This is already hardcoded in config/secrets.yml for development and
testing environments.
=> Remove SECRET_KEY_BASE

app/controllers/setup_controller.rb, app/models/pillar.rb, spec/controllers/setup_controller_spec.rb
so it can be used from the Minions to access the salt master etc.
=> Set "dashboard" Pillar to the request.host value

app/assets/javascripts/dashboard.js, app/views/setup/discovery.html.slim
=> discovery: don't allow empty bootstrap

app/controllers/setup_controller.rb, spec/controllers/setup_controller_spec.rb
=> bootstrap: don't allow empty bootstrap in the back-end

app/views/setup/worker_bootstrap.html.slim
=> Improve bootstrap documentation

packaging/suse/patches/1_set_default_salt_events_alter_time_column_value.rpm.patch
=> packaging: rebase patch

kubernetes/manifest-templates/etcd.yaml, kubernetes/manifest-templates/private.yaml, kubernetes/manifest-templates/public.yaml
we always want to test the latest code in our development setup
=> manifest-templates: always use the latest images

config/environments/development.rb, config/environments/test.rb, config/initializers/secrets.rb, kubernetes/manifest-templates/public.yaml, lib/velum/secrets.rb, spec/lib/velum/secrets_spec.rb
follow up of https://github.com/kubic-project/velum/pull/110
=> Store and retrieve secret_key_base from disk file

db/seeds.rb
Create separate functions so it's very easy to visually identify what
gets seeded when.
=> Add seeding depending on environment

app/assets/javascripts/dashboard.js
As the data structure changes between bootstrap and monitoring, we
have to account for both in the code. This change will prevent the
exception without affecting behaviour.
=> Prevent exception in console during initial bootstrap

kubernetes/start
* remove unneeded --allow-privileged flag. (defaults to false)
=> make kubelet's log level configurable

app/assets/javascripts/dashboard.js, app/controllers/concerns/discovery.rb, app/controllers/dashboard_controller.rb, app/controllers/setup_controller.rb, app/views/setup/discovery.html.slim
I've also merged some code that was shared between the dashboard and the
setup controllers.
Fixes bsc#1036040
=> Fixed the node count on the discovery page

docs/salt-job-callbacks.md
Open sourcing an internal research that was done by @jimmykarily.
=> docs: added internal research on salt job callbacks

packaging/suse/velum.spec.in
this is not allowed in distributions according to the FSH
=> packaging: use /usr/share instead of /usr/local

app/controllers/health_controller.rb, config/routes.rb, spec/controllers/health_controller_spec.rb
=> Added a /_health endpoint

app/models/minion.rb, db/migrate/20170512100610_remove_uniqueness_from_minion_fqdn.rb, db/schema.rb, spec/models/minion_spec.rb, spec/models/salt_handler/minion_start_spec.rb
We will allow duplicated fqdns in the discovery list.
Fixes: bsc#1031623
=> Do not check for uniqueness in fqdn attribute

app/views/dashboard/autoyast.xml.erb
=> Fix patterns on autoyast

app/models/pillar.rb, app/views/setup/welcome.html.slim, lib/velum/kubernetes.rb
=> Add setting for the main apiserver hostname

app/views/dashboard/autoyast.xml.erb
=> autoyast: added docker

app/controllers/setup_controller.rb, app/models/pillar.rb, app/validators/alphabetic_validator.rb, spec/controllers/setup_controller_spec.rb, spec/models/pillar_spec.rb
I've also fixed a redirect.
See bsc#1031475
=> setup: Block non-alphabetical characters

app/views/devise/registrations/new.html.slim
=> signup: added proper validation message for the password fields

lib/velum/salt.rb
The fixes Salt 2016.11.3 and 2016.11.4 compatibility.
=> Fix compatibility with salt 2016.11.4

app/controllers/setup_controller.rb, app/models/pillar.rb, app/views/setup/welcome.html.slim
See kubic-project/salt#66
See bsc#1036627
=> Added Docker HTTP proxy settings

Gemfile, Gemfile.lock, app/models/minion.rb, spec/controllers/salt_controller_spec.rb, spec/controllers/updates_controller_spec.rb, spec/features/admin_node_update_feature_spec.rb, spec/features/dashboard_feature_spec.rb, spec/support/capybara.rb, spec/support/wait_for_events.rb
=> Fixed flaky tests

.travis.yml, Gemfile, Gemfile.lock, spec/support/capybara.rb
Check if this makes our Travis CI more stable.
Add phantomjs to travis configuration
=> Remove phantomjs gem

app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/setup_controller.rb
@mssola`s review can be found at https://github.com/kubic-project/velum/pull/201#pullrequestreview-45357751.
=> Missing improvements from #201 (add unassigned nodes)

app/assets/javascripts/dashboard.js, app/helpers/application_helper.rb, app/views/setup/discovery.html.slim, spec/features/bootstrap_cluster_feature_spec.rb
This is a simple cosmetic trying to improve the UX of our end users. I know that there are some duplicated code but decided to do that way to make things easier to read/understand and simpler code-wise (less js changes).
=> ui: discovery page layout enhancement

app/views/setup/discovery.html.slim
=> Clarification on the discovery page

config/routes.rb
=> Only restrict routes on production

app/assets/javascripts/dashboard.js, app/views/setup/discovery.html.slim
=> hide minimum nodes alert (bsc#1046626)

.travis.yml
Also improve caching for faster builds.
=> Make travis load the required phantomjs version

app/views/setup/worker_bootstrap.html.slim
such contribution, much wow.
fixes: https://github.com/kubic-project/velum/issues/240
=> views: remove lore ipsum dead code from worker_bootstrap.html.slim

lib/velum/kubernetes.rb
Fixes: bsc#1046963
Depends on: https://github.com/kubic-project/salt/pull/150
=> Download the kubectl client certificate and key from the new location

public/503_database_not_ready.html
Try to use the same style as the main velum web application. This is something I hacked together in a couple of minutes. I think @vitoravelino will have lots of comments about that :)
=> Improve the style of "db is initializing" page [bsc#1047305]

public/404.html, public/422.html, public/500.html, public/503_database_not_ready.html
we need to keep all the static pages in sync with css styles:
=> adapt style of static pages - follow up #237

.travis.yml, app/assets/javascripts/dashboard.js, spec/features/add_unassigned_nodes_feature_spec.rb, spec/features/admin_node_update_feature_spec.rb, spec/features/auth/login_feature_spec.rb, spec/features/bootstrap_cluster_feature_spec.rb, spec/features/monitoring_feature_spec.rb, spec/support/capybara.rb, spec/support/helpers.rb, spec/support/wait_for_events.rb
This is an effort to fix flaky tests from our test suite.
Thanks to @mssola and @vitoravelino.
=> Fix flaky tests

app/assets/javascripts/dashboard.js, app/views/setup/discovery.html.slim
=> bootstrap: added titles to checkboxes and radio (bsc#1046035)

config/puma.rb
this allows for more concurrent api requests
a worker spawns a copy of the velum process
Backport of: https://github.com/kubic-project/velum/pull/257
=> increase workers (bsc#1048533)

app/assets/javascripts/dashboard.js, spec/features/dashboard_feature_spec.rb
PR against master: https://github.com/kubic-project/velum/pull/262
Depends on: https://github.com/kubic-project/velum/pull/263
=> Backport for bsc#1049165

config/initializers/session_store.rb
=> set secure flag in cookie (bsc#1050484)

bin/init
there is a gap between the database setup and the start of the rails
server which can be reduced
=> reduce 503 gap (bsc#1049931)

app/assets/javascripts/dashboard.js
~~still need to test it~~
tested and works as expected
=> allow kubeconfig download when master is ready (bsc#1048483)

app/views/devise/registrations/new.html.slim, app/views/devise/sessions/new.html.slim
I know it's nitpicky, but my OCD requires me to finally change this
text.
=> Small grammar update

app/assets/javascripts/dashboard.js
(cherry picked from commit 4d07cc542c3cb1fd29a3845c63dea15e63384aa1)
Backport of https://github.com/kubic-project/velum/pull/269
=> [1.0] allow kubeconfig download when master is ready (bsc#1048483)

app/views/setup/welcome.html.slim
Fix typo from 127.0.01 -> 127.0.0.1
Fixes bsc#1052759
Backport of https://github.com/kubic-project/velum/pull/267
=> [1.0] Fix loopback IP for proxy exception during initial configuration

app/assets/javascripts/dashboard.js, app/assets/stylesheets/pages/nodes_list.scss, app/assets/stylesheets/velum_bootstrap-variables.sass, app/views/setup/discovery.html.slim, spec/features/bootstrap_cluster_feature_spec.rb
Allow the user to choose multiple masters during the initial
bootstrap.
We don't currently allow for adding a master post bootstrap.
Depends-On: https://github.com/kubic-project/automation/pull/40
Depends-On: https://github.com/kubic-project/automation/pull/60
=> Allow multiple master selection

lib/tasks/velum.rake
This rake task takes two parameters: an email and a password, and will
create a user entry in the Velum database so it's possible to login and
work with it.
=> Add rake task velum:create_user

app/views/dashboard/autoyast.xml.erb
=> Add a 200MB EFI partition to AutoYaST XML

.travis.yml
=> fix travis for mysql-devel

app/models/pillar.rb, app/views/setup/bootstrap.html.slim
Depends on https://github.com/kubic-project/salt/pull/193
=> Adding option to install Tiller

app/controllers/setup_controller.rb, db/migrate/20170911123313_set_etcd2_as_default_backend.rb, db/schema.rb
Depends on: https://github.com/kubic-project/salt/pull/224
=> Set etcd2 backend for old installations

app/controllers/setup_controller.rb, app/models/pillar.rb, app/views/setup/bootstrap.html.slim, app/views/setup/welcome.html.slim
Backport of https://github.com/kubic-project/velum/pull/316
=> Re-adding option to install Tiller

app/models/pillar.rb
Re: https://github.com/kubic-project/salt/commit/408ab7a408ca6b41717d2072acf2b18f46c4a7e7
=> Update pillar documentation reference

app/assets/images/logo.svg, app/assets/stylesheets/velum_general.scss, app/views/shared/_header.html.slim
with the full name SUSE® CaaS Platform
bsc#1062247
(cherry picked from commit b2ed55d9793154195654b0b7312f7eed22e3313c)
Backport of https://github.com/kubic-project/velum/pull/324
=> [2.0] add new svg logo

config/environments/production.rb
the logo has recently changed to svg and needs to be compiled too
otherwise it wont be shown
bsc#1062878
=> also compile svg

config/environments/production.rb, spec/features/bootstrap_cluster_feature_spec.rb
Backport of https://github.com/kubic-project/velum/pull/336
=> [2.0] fix travis

app/views/setup/welcome.html.slim
=> better explain internal dashboard fqdn

app/views/setup/welcome.html.slim
bsc#1063233
(cherry picked from commit 835aa114619d0f031756241f909c7d29d24101cd)
Backport of https://github.com/kubic-project/velum/pull/339
=> [2.0] better explain internal dashboard fqdn

app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/oidc_controller.rb, spec/controllers/oidc_controller_spec.rb
Backport of https://github.com/kubic-project/velum/pull/331
=> [2.0] make sure request comes from a registered host

app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/oidc_controller.rb
Also, do not repeat the allowed hosts if they match.
=> Reuse filter logic for known hosts

app/controllers/application_controller.rb, app/controllers/oidc_controller.rb, app/views/oidc/done.html.slim, app/views/oidc/kubeconfig.erb, config/routes.rb, spec/controllers/oidc_controller_spec.rb
=> Make Dex first redirect to Velum, and download the kubeconfig file from there

db/migrate/20171027115228_add_remember_token.rb, db/schema.rb
=> enable remembering users

app/assets/stylesheets/pages/nodes_list.scss
=> Fixed role column broken up on two lines

app/controllers/concerns/api.rb, app/controllers/internal_api/v1/pillars_controller.rb, app/controllers/internal_api_controller.rb, app/models/pillar.rb, config/brakeman.ignore, config/initializers/internal_api.rb, config/routes.rb, spec/controllers/internal_api/v1/pillars_controller_spec.rb, spec/controllers/internal_api_controller_spec.rb, spec/spec_helper.rb, spec/support/api_helper.rb
Depends on:
* https://github.com/kubic-project/salt/pull/238
* https://github.com/kubic-project/caasp-container-manifests/pull/116
Fixes: bsc#1069145
=> Implement Pillar endpoint and introduce internal-api

spec/spec_helper.rb, spec/support/database_cleaner.rb
http://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/HookArgument
=> Omit the default :each argument for RSpec hooks.

packaging/suse/patches/0_change_versions.gem.patch
=> rebase patch

packaging/suse/patches/0_change_versions.gem.patch
=> rebase patch again since rake changed again

app/models/pillar.rb, lib/tasks/velum.rake
During [initialization](https://github.com/SUSE/pubcloud/blob/master/generic/src/CaaSP/caasp-admin-setup/caasp-admin-setup#L785) in the public cloud, the cloud framework is detected, and injected into velum as a pillar, using the rake task defined here.
=> Inject cloud framework

.travis.yml
see https://github.com/travis-ci/travis-ci/issues/8978
=> fix test for 2.5 in travis by updating the rubygems

packaging/suse/velum.spec.in
* addressing some duplicated file listings
* making spec file usable in factory as well
* drop some slashes that are already contained in velumdir
=> Spec enhancements

Gemfile.lock
=> bump uglifier

Gemfile, Gemfile.lock, packaging/suse/bundler-dumpdeps, packaging/suse/make_spec.sh, packaging/suse/patches/1_nodev.gem.patch, packaging/suse/velum.spec.in
this will help reduce the breakages in factory
=> dont be strict with gems

spec/features/auth/login_feature_spec.rb
I had issues with a failing test that used inconsitent access to the 'Log in' button, so I've updated it to match the rest of the spec.
Additionally, the descriptions didn't make sense in documentation format so I reworded them.
=> Update login feature spec

app/controllers/oidc_controller.rb, app/views/oidc/done.html.slim, app/views/oidc/kubeconfig.erb
Add instructions for manually adding a cluster to a pre-existing
kubeconfig file.
=> Add manual kubeconfig setup instructions

app/assets/javascripts/setup/setup.js, app/controllers/internal_api/v1/pillars_controller.rb, app/controllers/setup_controller.rb, app/helpers/setup_helper.rb, app/models/pillar.rb, app/views/setup/cloud/_openstack_configuration.html.slim, app/views/setup/cloud/_settings.html.slim, app/views/setup/welcome.html.slim, spec/controllers/internal_api/v1/pillars_controller_spec.rb, spec/controllers/setup_controller_spec.rb, spec/factories/pillar_factory.rb, spec/features/bootstrap_settings_feature_spec.rb
=> Added CPI configuration

Gemfile.lock
=> update loofah to fix xss vulnerability

app/models/user.rb, spec/models/user_spec.rb
=> Migrate LDAP passwords

app/controllers/setup_controller.rb
=> Fix rubocop offenses

app/assets/javascripts/dashboard/dashboard.js, app/controllers/concerns/discovery.rb, app/controllers/setup_controller.rb, app/models/cloud_cluster.rb, app/models/salt_event.rb, app/models/salt_handler/cloud_bootstrap.rb, app/models/salt_job.rb, app/views/setup/discovery.html.slim, db/migrate/20180427014552_create_salt_jobs.rb, db/schema.rb, packaging/suse/patches/1_set_default_salt_events_alter_time_column_value.rpm.patch, spec/controllers/setup_controller_spec.rb, spec/factories/salt_job_factory.rb, spec/features/bootstrap_cluster_feature_spec.rb, spec/models/cloud_cluster_spec.rb, spec/models/salt_handler/cloud_bootstrap_spec.rb, spec/models/salt_job_spec.rb, spec/vcr_cassettes/salt/cloud_profile.yml, spec/vcr_cassettes/salt/login_500.yml
#502 cherry-picked and backported for inclusion to release-2.1
=> Salt cloud feedback - r2.1

app/assets/javascripts/dashboard/dashboard.js, app/controllers/concerns/discovery.rb, app/controllers/setup_controller.rb, app/models/cloud_cluster.rb, app/models/salt_event.rb, app/models/salt_handler/cloud_bootstrap.rb, app/models/salt_job.rb, app/views/setup/discovery.html.slim, db/migrate/20180427014552_create_salt_jobs.rb, db/schema.rb, packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch, spec/controllers/setup_controller_spec.rb, spec/factories/salt_job_factory.rb, spec/features/bootstrap_cluster_feature_spec.rb, spec/models/cloud_cluster_spec.rb, spec/models/salt_handler/cloud_bootstrap_spec.rb, spec/models/salt_job_spec.rb, spec/vcr_cassettes/salt/cloud_profile.yml, spec/vcr_cassettes/salt/login_500.yml
#502 cherry-picked for inclusion to release-3.0
=> Salt cloud feedback - r3.0

app/assets/javascripts/cloud/bootstrap.js
#507 cherry-picked for inclusion to release-3.0
=> Prevent double-clicking setup#bootstrap submit in public cloud - r3.0

app/controllers/application_controller.rb, app/models/pillar.rb
=> [bsc#1087447] validate pillars

app/assets/stylesheets/components/header.scss, app/assets/stylesheets/velum_general.scss, app/controllers/internal_api/v1/pillars_controller.rb, app/controllers/settings/kubelet_compute_resources_reservations_controller.rb, app/helpers/settings_helper.rb, app/models/kubelet_compute_resources_reservation.rb, app/views/layouts/application.html.slim, app/views/layouts/settings.html.slim, app/views/settings/_sidebar.html.slim, app/views/settings/kubelet_compute_resources_reservations/_resources.html.slim, app/views/settings/kubelet_compute_resources_reservations/index.html.slim, config/routes.rb, db/migrate/20180508070232_create_kubelet_compute_resources_reservations.rb, db/schema.rb, packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch, spec/controllers/internal_api/v1/pillars_controller_spec.rb, spec/controllers/settings/kubelet_compute_resources_reservations_controller_spec.rb, spec/factories/kubelet_compute_resources_reservation.rb, spec/models/kubelet_compute_resources_reservation_spec.rb
Backport of https://github.com/kubic-project/velum/pull/514
fixes bsc#1086185
=> [3.0] Handle kubelet resource reservations

app/controllers/application_controller.rb, app/models/pillar.rb
backport of https://github.com/kubic-project/velum/pull/522
=> [3.0][bsc#1087447] validate pillars

app/assets/stylesheets/velum_bootstrap-variables.sass, app/views/settings/_apply.html.slim
backport of https://github.com/kubic-project/velum/pull/523
=> [3.0]  emphasize settings apply workflow

app/controllers/settings/auditing_controller.rb, app/helpers/settings_helper.rb, app/models/pillar.rb, app/views/settings/_sidebar.html.slim, app/views/settings/auditing/index.html.slim, config/routes.rb, spec/controllers/settings/auditing_controller_spec.rb
Backport of https://github.com/kubic-project/velum/pull/532
=> Provide UI to manage kubernetes auditing

app/assets/javascripts/dashboard/dashboard.js
Also replaced deprecated ajax callback method.
bsc#1093869 follow-up
=> ui: fixed unwanted acceptance failure alert 

packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
this will fix the package build in 2.1
packaging#fix-build
similar to #525 but not a straight backport
=> [2.1] rebase patch

packaging/suse/velum.spec.in
=> Make use of %license macro

app/controllers/setup_controller.rb, app/models/pillar.rb, app/views/setup/welcome.html.slim
This reverts commit d7a11f41eaa528cc65e1a17aa1e63765d25e020f.
=> Revert "Allow users to choose flannel's backend"

packaging/suse/velum.spec.in
=> update velum requirements on mariadb for sle15

app/views/setup/welcome.html.slim
Backport of #561.
(cherry picked from commit 5334257e0067ba9e1a69afe387bf3867815cf5e2)
=> [3.0] Fix bsc#1062186: update tooltip to explain possible dashboard values.

app/views/setup/welcome.html.slim
Backport of #561 
(cherry picked from commit 5334257e0067ba9e1a69afe387bf3867815cf5e2)
=> [2.1] Fix bsc#1062186: update tooltip to explain possible dashboard values.

app/views/dashboard/modals/_warn_node_force_removal_modal.html.slim
enhancement#fix-forced-removal-modal-paragraphs
=> ui: fix forced node removal modal paragraphs

app/views/dashboard/modals/_warn_node_force_removal_modal.html.slim
Backport of https://github.com/kubic-project/velum/pull/567
=> Release 3.0 backport fix ui node removal paragraphs

public/503.html
=> make 503 page more generic

spec/features/bootstrap_in_azure_feature_spec.rb
Most of the content is covered in the cloud_cluster model, but there are a few differentiators that should be checked.
=> Add a feature spec for building cluster in Azure

Gemfile.lock
=> update sprockets to fix cve-2018-3760 cve#2018-3760

app/controllers/settings/base_certificate_controller.rb, app/controllers/settings/dex_connector_ldaps_controller.rb, app/controllers/settings/registries_controller.rb, app/controllers/settings/registry_mirrors_controller.rb, app/controllers/settings/system_certificates_controller.rb, app/controllers/setup_controller.rb, app/models/certificate.rb, app/models/system_certificate.rb, app/views/settings/dex_connector_ldaps/_form.html.slim, app/views/settings/registries/_form.html.slim, app/views/settings/registry_mirrors/_form.html.slim, app/views/settings/system_certificates/_fields.html.slim, app/views/settings/system_certificates/_form.html.slim, spec/controllers/settings/dex_connector_ldaps_controller_spec.rb, spec/controllers/settings/registries_controller_spec.rb, spec/controllers/settings/registry_mirrors_controller_spec.rb, spec/controllers/settings/system_certificates_controller_spec.rb, spec/controllers/setup_controller_spec.rb, spec/features/settings/dex_connector_ldap_feature_spec.rb, spec/features/settings/mirrors_feature_spec.rb, spec/features/settings/registries_feature_spec.rb, spec/rails_helper.rb
=> Allow uploading certificates via file

app/views/oidc/done.html.slim
=> Fix smally typo

app/controllers/setup_controller.rb, app/views/setup/worker_bootstrap_azure.html.slim, app/views/setup/worker_bootstrap_ec2.html.slim, app/views/setup/worker_bootstrap_gce.html.slim
* Requires #595
* Requires #610
Adapt public cloud bootstrap views & controller actions to enable adding nodes after boostrap.
=> bsc#1098085 Add nodes in public clouds

app/models/certificate.rb, app/validators/x509_certificate_validator.rb, spec/controllers/internal_api/v1/pillars_controller_spec.rb, spec/controllers/settings/registries_controller_spec.rb, spec/controllers/settings/registry_mirrors_controller_spec.rb, spec/controllers/settings/system_certificates_controller_spec.rb, spec/controllers/setup_controller_spec.rb, spec/factories/certificate_factory.rb, spec/features/settings/mirrors_feature_spec.rb, spec/features/settings/registries_feature_spec.rb, spec/models/certificate_spec.rb, spec/rails_helper.rb
=> [3.0] bsc1097754: certificate verification

app/assets/javascripts/dashboard/dashboard.js, app/models/minion.rb, app/views/dashboard/index.html.slim, bin/init, db/migrate/20181708070233_add_online_status_to_minions.rb, db/schema.rb, packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch, spec/features/monitoring_feature_spec.rb
backport of https://github.com/kubic-project/velum/pull/594
=> [3.0] save online status through reconciler (bsc#1098436)

app/models/minion.rb
=> Update the minion hostname in a regular basis, based on the grain information.

app/controllers/internal_api/v1/pillars_controller.rb, app/controllers/setup_controller.rb, app/models/cloud_cluster.rb, app/models/pillar.rb, app/views/setup/worker_bootstrap_azure.html.slim, app/views/setup/worker_bootstrap_ec2.html.slim, app/views/setup/worker_bootstrap_gce.html.slim, spec/controllers/internal_api/v1/pillars_controller_spec.rb, spec/controllers/setup_controller_spec.rb, spec/factories/pillar_factory.rb, spec/features/bootstrap_in_gce_feature_spec.rb, spec/models/cloud_cluster_spec.rb
(cherry picked from commit 446f412a3fd871bfae8429d9131fe462cbbb0d5e)
=> [3.0] Public Cloud: Add support for bootstrapping in Google Compute

spec/features/bootstrap_in_azure_feature_spec.rb
=> [3.0] Add a feature spec for building cluster in Azure

app/assets/javascripts/settings/ldap-conn-test.js, app/controllers/settings/dex_connector_ldaps_controller.rb, app/controllers/settings/ldap_test_controller.rb, spec/controllers/settings/ldap_test_controller_spec.rb
Corrected fetching of password for ldap external auth
Corrected grabbing of certificate content for validating ldap external auth
=> Fix test connection button for ldap external auth

spec/controllers/internal_api/v1/pillars_controller_spec.rb
=> specs: fixed minor mismatching expectation

app/assets/javascripts/dashboard/dashboard.js
=> [bsc#1108740] dont allow updating admin again when cluster update failed

spec/controllers/internal_api/v1/pillars_controller_spec.rb
I noticed that a couple of pillar test cases were passing despite an error in the test.  This PR adjusts those test cases so they correctly fail upon discrepancies.
Ultimately, this ended up being a fairly significant refactor of the test code, but the test still actually works the same way; it's just a bit more concise.
=> Fix broken LDAP connector test case syntax

.gitignore, README.md, app/assets/javascripts/dashboard/dashboard.js, app/controllers/salt_controller.rb, app/models/minion.rb, app/models/salt_event.rb, app/models/salt_handler/auth_event.rb, app/views/dashboard/unassigned_nodes.html.slim, app/views/setup/discovery.html.slim, config/routes.rb, lib/velum/salt.rb, spec/features/bootstrap_cluster_feature_spec.rb, spec/features/dashboard_feature_spec.rb, spec/lib/velum/salt_spec.rb, spec/models/minion_spec.rb, spec/models/salt_event_spec.rb, spec/models/salt_handler/auth_event_spec.rb, spec/support/utils.rb, spec/vcr_cassettes/salt/reject_minion.yml, spec/vcr_cassettes/salt/remove_minion.yml
Adds following actions:
- Remove unassigned nodes
- Reject nodes
depends-on [pr](https://github.com/kubic-project/automation/pull/496)
[Bug](https://bugzilla.suse.com/show_bug.cgi?id=1099985)
=> [3.0] FIX bsc#1099985 removes unassigned nodes and add a reject node link

app/models/salt_event.rb, config/brakeman.ignore
(cherry picked from commit 97b888dd631d4905bc58001788282f5be86fb76a)
=> [3.0] Fix alter_time format when deleting old data (bsc#1112967)

app/views/settings/dex_connector_ldaps/_form.html.slim
=> ldap: minor fix field value example

lib/velum/salt.rb, spec/lib/velum/salt_spec.rb, spec/vcr_cassettes/salt/reject_minion.yml, spec/vcr_cassettes/salt/remove_minion.yml
This fixes the part of parsing the wrong object field from https://bugzilla.novell.com/show_bug.cgi?id=1117152
=> Partial fix of bsc#1117152: do not parse the return code but the JSON response.

app/assets/javascripts/setup/openstack.js
(cherry picked from commit 388521f05df086a00c5a2885df10e9ec369281d1)
=> [3.0] [CPI] Split logic for Project and Domain ID, bsc#1103873

app/controllers/internal_api/v1/pillars_controller.rb, app/controllers/settings/dex_connector_oidcs_controller.rb, app/helpers/settings_helper.rb, app/models/dex_connector_oidc.rb, app/validators/http_url_validator.rb, app/validators/oidc_provider_validator.rb, app/views/settings/_sidebar.html.slim, app/views/settings/dex_connector_oidcs/_form.html.slim, app/views/settings/dex_connector_oidcs/edit.html.slim, app/views/settings/dex_connector_oidcs/index.html.slim, app/views/settings/dex_connector_oidcs/new.html.slim, app/views/settings/dex_connector_oidcs/show.html.slim, config/initializers/filter_parameter_logging.rb, config/routes.rb, db/migrate/20182106194300_create_dex_connectors_oidc.rb, db/schema.rb, docs/oidc_testing/README.md, docs/oidc_testing/docker-compose.yml, docs/oidc_testing/examples/.gitignore, docs/oidc_testing/examples/config-dev.yaml.example, lib/velum/dex/oidc.rb, spec/controllers/internal_api/v1/pillars_controller_spec.rb, spec/controllers/settings/dex_connector_oidcs_controller_spec.rb, spec/factories/dex_connectors_oidc_factory.rb, spec/features/settings/dex_connector_oidc_feature_spec.rb, spec/models/dex_connector_oidc_spec.rb, spec/spec_helper.rb, spec/support/database_cleaner.rb, spec/vcr_cassettes/oidc/invalid_connector.yml, spec/vcr_cassettes/oidc/validate_connector.yml
Backport PR #665 to 3.0 release.  WIP as a communication placeholder until I get through the tests.
=> 3.0-backport: OIDC Connector support (bsc#1116376)

app/views/oidc/done.html.slim
=> oidc: fixed instructions for manual configuration (bsc#1123711)

app/views/oidc/done.html.slim
=> [3.0] oidc: fixed instructions for manual configuration (bsc#1123711)
