kubic-project/velum

- spec/controllers/nodes_controller_spec.rb
- spec/lib/pharos/salt_api_spec.rb
- spec/lib/pharos/salt_minion_spec.rb
- spec/lib/pharos/salt_spec.rb
- spec/spec_helper.rb
Instead, set them on the spec_helper, so we ensure that we aren't
missing this envvars that will help us to mock requests with VCR.
> Remove envvars from specific tests

- app/models/minion.rb
- lib/pharos/salt_api.rb
- spec/lib/pharos/salt_api_spec.rb
- spec/models/minion_spec.rb
If we cannot set the role on the remote, make sure that the transaction
gets a rollback, so we have the same information on the local database
than the remote salt instance.
> Add minion missing test

- Gemfile
- Gemfile.lock
- app/controllers/nodes_controller.rb
- app/models/minion.rb
- lib/pharos/salt_minion.rb
- spec/controllers/nodes_controller_spec.rb
- spec/lib/pharos/salt_minion_spec.rb
- spec/models/minion_spec.rb
Also trust our database and don't query salt for already applied roles
> Create assign_roles method on Minion and remove keyword args

- kubernetes/start
otherwise the setup-environment process will be spawned into the
background and continues to run and spam the teminal even when the
start script failed
> setup: check for kubelet before trying to execute it

- lib/pharos/salt.rb
- spec/lib/pharos/salt_spec.rb
This exposes less salt slang to the Pharos::Salt users.
> Update the salt interface to take action and a default targets: '*'

- packaging/suse/.gitignore
- packaging/suse/make_spec.sh
- packaging/suse/velum.spec.in
It's still a bit bad to have the `make_spec.sh` script duplicated between here and `Portus`.
But there is some work on the way to fix that (see https://github.com/openSUSE/ruby-packaging/pull/6)
> packaging: add files for packaging velum in openbuildservice

- kubernetes/manifest-templates/etcd.yaml
- kubernetes/start
- lib/velum/salt_minion.rb
When there is no dashboard, the development environment is the
dashboard itself. Add an etcd instance that the rest of the cluster
can use.
> Add an etcd instance to the development environment.

- README.md
- kubernetes/start
We need the non interactive mode for the script to be used from other
scripts (e.g. in the e2e-tests project)
> Use --non-interactive flag for non interactive mode in dev env start script

- packaging/suse/concourse/README.md
- packaging/suse/concourse/package.sh
this will be called by a concourse task during execution of the
pipeline, and prepares an osc-resource to be submitted to obs
> packaging: add a script to prepare obs submission

- packaging/suse/concourse/package.sh
when submitting the specfile we also need the new tarball
> packaging: fetch newest tarball from github

- packaging/suse/make_spec.sh
when we call make_spec.sh within a concourse git resource, the git
command renders HEAD instead of master.
> packaging: reference master instead of HEAD

- packaging/suse/concourse/wait_for_build.sh
as obs is a bit slow picking up a new build once a new change has
been submitted, we need an intermediate step to make sure the build
has begun, before checking for success/failure
> packaging: make sure build is running, obs is slow

- packaging/suse/concourse/buildresult.sh
in the case that build jobs have been processed, but new repository
is not yet created (meaning the package hasn't been published yet), the output of the query will look like:
SLE_12_SP2 x86_64 succeeded*
so we need to adapt the regex to that case as it can take up quite some time to get published
> packaging: adapt regex to obs output

- packaging/suse/concourse/buildresult.sh
- packaging/suse/concourse/copypac.sh
- packaging/suse/concourse/wait_for_build.sh
* make sure to write .oscrc
* enhance logging
* cache result after success
otherwise we will always fail, due to an outdated result
if the apiurl is different than https://api.opensuse.org
> packaging: enhancements and fixes

- .gitignore
- kubernetes/manifest-templates/salt.yaml
- kubernetes/salt-templates/pillar/vars.sls
- kubernetes/start
When starting the development environment, we can take the vars.sls
from the pillar, and mount it on the salt-master, so we can add some
variables without having to modify the original salt states.
> Set dashboard location on the pillar.

- app/models/pillar.rb
- db/migrate/20170227152008_create_pillars.rb
- db/schema.rb
- docs/salt.md
- kubernetes/salt/config/master.d/salt-master.conf
- spec/factories/pillar_factory.rb
- spec/models/pillar_spec.rb
The pillar is not programatically modifiable. Since we need to set
some pillar values during the bootstrapping process, we need to rely
on an external pillar that we can modify.
The original module requires a '%s' argument to be provided, or the
mysql python module will complain. We added a `minion_id` that can be
used for certain pillar key discovery. However, since we are going to
use this pillar information for global configuration, we can just let
`minion_id` be NULL, and that will be readable by all salt clients.
We also add a Pillar model that will be able to modify these Pillar
values.
> Add an external pillar.

- packaging/suse/patches/0_change_versions.gem.patch
This is a commit which has been merged into master about requiring
"recusive-open-struct ~> 1.0.0"
instead of
"recursive-open-struct =1.0.0"
thus we can use the latest version of recursive-open-struct (1.0.2).
This simplifies creating the rpm
> relax requirement on recursive-open-struct gem

- Dockerfile
because now we have js test that need it.
> Update Dockerfile to also install phantomjs

- packaging/suse/velum.spec.in
unfortunately there is no option to patch that prevents this
it seems that patch creates an .orig file in some cases even
when it was successful, e.g. when the patch has an offset
> packaging: remove .orig files

- app/models/salt_handler/minion_highstate.rb
Not only the `success` field indicates a successfull highstate
execution, but also the `retcode` field being 0 as a result of the
execution.
> Check retcode return value of the highstate

- .travis.yml
- app/controllers/dashboard_controller.rb
- app/views/dashboard/autoyast.xml.erb
- app/views/setup/worker_bootstrap.html.slim
- config/brakeman.ignore
- config/environments/test.rb
- config/routes.rb
- lib/velum/http_exceptions.rb
- lib/velum/salt_api.rb
- lib/velum/suse_connect.rb
- spec/controllers/dashboard_controller_spec.rb
- spec/lib/velum/salt_api_spec.rb
- spec/lib/velum/suse_connect_spec.rb
- spec/vcr_cassettes/suse_connect/caasp_registration_active.yml
- spec/vcr_cassettes/suse_connect/invalid_credentials.yml
- spec/vcr_cassettes/suse_connect/no_caasp_registration_active.yml
This profile will be read by workers during the bootstrapping process
and when adding new workers to the cluster. It will provide the
subscription details of the main installation to the workers.
Here we take into account that we are using our SUSE Secrets fork of
Docker, that mounts `/run/secrets` on every container. This directory
will include `/etc/SUSEConnect` and `/etc/zypp/credentials.d` from the
host mounted inside the container.
- `/run/secrets/SUSEConnect` includes the SMT if any (the default is SCC
if not provided). If there is a SMT present, the regcode will be empty.
- If we are using SUSE's Customer Center (SCC), we need a regcode, that
is obtained using the credentials in
`/run/secrets/credentials.d/SCCcredentials` file, accessing the SCC API
and checking for an active …
> Add AutoYaST profile serving

- app/controllers/dashboard_controller.rb
Since `Socket.gethostname` can be a purely internal hostname (not
exposed to other machines) and since the customer is in charge of
DNS itself, and since `@controller_node` here is going to be used
to provide a reachable salt master hostname for the rest of the
workers, it's better to just use the same hostname the customer used
when added the `autoyast=http://fancy-host.fancy-domain/autoyast`. In
this case we don't care about the internal name `Socket.gethostname`
but about the external name (the customer already used it on their own
request, so we just retrieve it).
> Retrieve host from request

- config/puma.rb
We are firing puma up with something along the lines:
`bundle exec rails s -b 0.0.0.0 -p 80 --pid /tmp/puma.pid Puma`
In this case, the port is set through an argument to the rails server
command, but with this change on our puma configuration, we override
it, only honoring the `PORT` envvar, or falling back to 3000
otherwise.
Remove this bit from the Puma configuration, since our manifests
include the port as an argument to the rails server command.
> Remove port from puma configuration

- bin/check_db.rb
- bin/init
add a wrapper script called init that will check if the database has
been configured and, in that case, it will configure it before starting
the rails server.
This script calls db:migrate because this is meant to be run in a container.
When velum is updated, it will be by launching a new container, thus the new
container should run db:migrate.
> add init for containers

- app/views/dashboard/autoyast.xml.erb
The files directive is executed on the 2nd YaST stage (which it's
skipped in CaaSP), so the `/etc/salt/minion.d/master.conf` was never
created on the worker nodes.
Let's do the same, but running a script that will create this
configuration file in the 1st YaST stage.
> Set salt master configuration on the minion on a script

- app/helpers/setup_helper.rb
- app/views/setup/welcome.html.slim
- config/country_codes.yml
like that we can drop the front-end validation, and it's more convenient
for the user
> setup: enable select field for the country codes

- lib/velum/kubernetes.rb
The ca certificate was retrieved from the mine. The mine gets wiped
when the admin node gets rebooted (the salt-master container gets
rebooted). We don't want to wait for the mine to be populated if we
actually have this information in the filesystem.
If an orchestration is run, this information will be automatically
populated on the mine (but we don't want to force that), so we
directly use salt to cat the ca certificate from the ca machine (it's
a container at the moment).
> Request the ca certificate directly to the CA machine (container)

- bin/init
- public/503_database_not_ready.html
run a mini server during the time that velum is waiting for the db
this avoids the awkward situation that nothing seems to happen directly
after the installation
https://bugzilla.suse.com/show_bug.cgi?id=1031682
> fix bsc#1031682

- kubernetes/salt/salt/orch/kubernetes.sls
- kubernetes/start
This will stop velum from starting with an empty SaltStack. Users were
intended to specify this value, but it wasn't enforced.
> Forcing a user to specify a SALT_DIR

- app/assets/javascripts/dashboard.js
- app/models/minion.rb
- app/models/salt_handler/minion_highstate.rb
- app/models/salt_handler/minion_start.rb
- app/views/setup/discovery.html.slim
- db/migrate/20170111154919_create_minions.rb
- db/migrate/20170124141701_add_uniq_index_on_minions_id.rb
- db/migrate/20170124170136_add_role_to_minions.rb
- db/schema.rb
- kubernetes/manifest-templates/public.yaml
- lib/velum/kubernetes.rb
- spec/controllers/setup_controller_spec.rb
- spec/factories/minions_factory.rb
- spec/factories/salt_event_factory.rb
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/features/monitoring_feature_spec.rb
- spec/models/minion_spec.rb
- spec/models/salt_event_spec.rb
- spec/models/salt_handler/minion_highstate_spec.rb
- spec/models/salt_handler/minion_start_spec.rb
- spec/vcr_cassettes/salt/process_event.yml
With this change we:
* Rename hostname to fqdn. Feels more correct.
* Do not assume on the salt part that the minion_id is the hostname/fqdn
* Explicitly save minion_id as a column, as well as fqdn as another column
* We will use minion_id internally to talk to salt, but show hostname, and
probably other properties [that we can cache in the very near future as
columns] like number of cores, memory, disk...
https://github.com/kubic-project/salt/pull/40
> Do not assume minion_id is hostname/fqdn

- app/views/dashboard/autoyast.xml.erb
Implement the changes suggested by @thkukuk in the `autoyast.xml` template for configuring NTP in the minions.
(see [this Trello card](https://trello.com/c/Orzhm7rZ))
> Added NTP configuration for nodes in autoyast.xml

- kubernetes/cleanup
- kubernetes/start
I was having a lot of trouble starting a cluster because I ended up with
two SaltStack files that were supposed to be UNIX sockets, but were
regular files instead.
Making the cleanup script clear out the manifests/ and tmp/ folders
Also making a change to the cleanup script suggested in #104
> Cleaning folders that can be problematic

- app/controllers/dashboard_controller.rb
- app/controllers/setup_controller.rb
- app/views/setup/welcome.html.slim
- app/views/setup/worker_bootstrap.html.slim
- db/seeds.rb
- spec/controllers/dashboard_controller_spec.rb
- spec/controllers/setup_controller_spec.rb
It will come with a reasonable default, but the person bootstrapping
the cluster will have the chance to set a different value so the
rest of the machines that will form part of the cluster will use this
reference during the bootstrapping process.
This modifies the workflow of the bootstrapping. To avoid problems, now
it's required for the customer/user to fill in all the first step
information in velum (registering first) for the autoyast profile to be
served (since it will contain a reference to the salt-master that will be
set on the rest of the machines). This way, the reference to the salt-master
on the autoyast profile, as well as the reference to the administration node
during the bootstrapping phase will be the one the customer/user set,
intead of being inferred from how the …
> Explicitly ask for the dashboard location

- kubernetes/cleanup
Re running the dev environment can fail to start from time to time if the old log files for the pods are still in place.
> Add /var/log/pods/* to cleanup script

- app/assets/javascripts/dashboard.js
- app/controllers/setup_controller.rb
- app/models/minion.rb
- app/views/setup/discovery.html.slim
- spec/controllers/setup_controller_spec.rb
- spec/models/minion_spec.rb
This change allows for the selection of multiple masters when bootstrapping
the cluster. Note that, this commit does not expose this functionality in
the UI. Allowing users to choose multiple masters will come further down the
line once HA deployments are working etc.
A second commit (which will land on a different branch) will expose this in the
UI for dev/test purposes.
> Internally support selection of multiple masters

- app/assets/javascripts/dashboard.js
When pressing the back/forward buttons in Chrome it sometimes returned a
JSON response for the HTML version. To avoid this, let's be explicit on
this and only allow JSON responses for requests ending with ".json"
(rails convention).
bsc#103174
> discovery: only send json responses to AJAX calls

- packaging/suse/velum.spec.in
Bundle install in `/usr/local/velum`, so in `/srv/velum` we only have
the source code.
> Do not bundle install in velum's source code location

- Gemfile
we are setting IGNORE_ASSETS=no from the spec file
that's why it was working, but it is not correct
> Gemfile: fix ENV

- packaging/suse/velum.spec.in
Set `.bundle/config` location by stripping the buildroot automatically added when installing with `--path`
> Set .bundle/config location by stripping the buildroot automatically

- app/views/setup/worker_bootstrap.html.slim
passing the VELUM_PORT to the autoyast_url helper makes sure to
always display the correct port, as the url helper seems to calculate
the port dynamically depending on where the request goes to.
if you forward the port locally via ssh, you will get this port
displayed which is wrong
> fix bsc#1036724

- app/views/dashboard/autoyast.xml.erb
fixes https://bugzilla.suse.com/show_bug.cgi?id=1034942
> autoyast: create /var/lib/docker partition (bsc#1034942)

- Vagrantfile
This allows a Velum dev VM and test workers (using the terraform setup) to be deployed on the same workstation. 
This wasn't supported before because the terraform setup deployed libvirt VMs and the current VagrantFile only supported  a VirtualBox VM. This leads to the following exception 
https://www.agix.com.au/kvm-error-ioctlkvm_create_vm-failed-16-device-or-resource-busy/
> Added support for libvirt deployment

- app/assets/stylesheets/velum_general.scss
If a page didn't fit users screen height, the footer overlaps any
element since its position is absolute to .container element.
An example of that was the "Next" button on initial configuration form.
See bsc#1041440
> Fixed footer overlapping elements

- app/assets/javascripts/dashboard.js
- app/views/setup/discovery.html.slim
Change the UI to show the salt ID (which now is set to be equal to the machine-id) instead of showing Rails' internal ID.
This is required to fix bsc#1041789
Note well: I'm still working on setting up the devenv to test this code, but I didn't want to hold the code on my machine.
> UI: show salt ID instead of rails' internal ID [bsc#1041789]

- app/models/minion.rb
- lib/velum/salt_minion.rb
- spec/controllers/setup_controller_spec.rb
- spec/factories/minions_factory.rb
- spec/models/minion_spec.rb
Internally we refer to `minion` as a salt minion generically, but
when it comes to assign roles (that will be shown to the user), fix
terminology and use `worker` instead of `minion`.
> Fix `minion` -> `worker` terminology

- packaging/suse/make_spec.sh
Let's use the git revision number in the version so that zypper will
see each new revision as an update. Otherwise, if we only use the commit
number, zypper gets confused
> fix version in package to be a sequence

- app/assets/javascripts/signup.js
- spec/features/auth/signup_feature_spec.rb
I had to add `checkValidity()` to force a manual check (the
same as when form is submitted) to avoid the weird default
suggestions and enforce the custom message.
See bsc#1041940
> signup: added proper email validation

- app/views/setup/welcome.html.slim
I know the UX of the cluster configuration page is still ongoing, but I think we can make a significant improvement with a few lines of code.
This is **not meant** to be the final look of the page, it's just something that we can can get out quickly before 1.0.
This is just something that I hacked together in between today's meeting thanks to my mad UI skills (yes, I'm kidding!)
This also helps with [bsc#1040367](https://bugzilla.suse.com/show_bug.cgi?id=1040367).
The different options have been grouped together based on their "topic":
For cryptic settings we could provide some contextual help, you can see that in action here:
> Improve cluster configuration page [bsc#1040367]

- app/assets/javascripts/dashboard.js
- app/controllers/concerns/discovery.rb
- app/controllers/updates_controller.rb
- app/models/minion.rb
- app/models/salt_handler/minion_start.rb
- app/views/dashboard/_update_admin_modal.html.erb
- app/views/dashboard/index.html.slim
- config/routes.rb
- lib/velum/salt.rb
- spec/controllers/dashboard_controller_spec.rb
- spec/controllers/setup_controller_spec.rb
- spec/controllers/updates_controller_spec.rb
- spec/features/admin_node_update_feature_spec.rb
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/features/dashboard_feature_spec.rb
- spec/features/monitoring_feature_spec.rb
- spec/lib/velum/salt_spec.rb
- spec/models/minion_spec.rb
- spec/support/utils.rb
- spec/vcr_cassettes/salt/update_status.yml
> Proper update detection and reboot of the admin node

- lib/velum/salt.rb
We are checking that the referenced file exists by performing a
rudimentary check. However, the result might be completely empty
under certain circumstances, making our check fail (`include?` called
on `nil` will fail).
This fixes the 500 error, but we still need to find out why the salt
side of things is failing at all to retrieve the contents of the
file.
Fixes: bsc#1043843
> Check that result isn't `nil` before checking result contents

- app/controllers/auth/registrations_controller.rb
- app/views/devise/sessions/new.html.slim
- spec/features/auth/signup_feature_spec.rb
The administration dashboard allows to create as many admin users as
desired, which is a potential security threat as Velum does not have any
user management. Besides, an admin cannot see how many other users
exist.
Avoid creating more than one admin user by not showing the
`Create an account` button when a user already exists. `users/sign_up`
will further redirect to the `root_path` and print an alert.
Notice that this is only an intermediate solution until multiuser
support and RBAC is implemented. Until then, a password reset must be
done by connecting to the machine (manually or via a script).
See bsc#1040831
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
See the screenshot below. The button is not displayed anymore and an 
alert is printed when forcefully visiting the …
> registration: allow only one admin user

- app/assets/javascripts/dashboard.js
- app/controllers/salt_controller.rb
- app/models/minion.rb
- app/models/salt_handler/minion_highstate.rb
- app/views/dashboard/index.html.slim
- config/routes.rb
- lib/velum/salt.rb
- spec/controllers/salt_controller_spec.rb
- spec/vcr_cassettes/salt/update_orch.yml
* Adds a button that will trigger the update orchestration
run, when there is nodes that can be updated.
* Updates the status column to show status of updates.
* Updated the Salt Event listener to update status of minions
marked as "failed" if another highstate succeeds
> Add "update workers" button to velum.

- app/assets/javascripts/dashboard.js
- app/models/minion.rb
For 1.0 we changed the layout of overview page. During that process,
I accidentally changed this piece of code without reminding that
the discovery page also depended on this.
Now it separates different behavior depending on the page.
> Fixed regression introduced when changed dashboard layout

- app/models/salt_handler/minion_highstate.rb
With the current logic, it could happen that during the same
orchestration run the first highstate succeeds (setting the minion
status to :applied as succeeded), while the second highstate fails
(and the :applied status as succeeded will be kept).
With this change we consider the latest highstate run is the most
recent, and whatever it reports is what the final status of the
minion will be.
> When setting the highstate resolution, consider all highstates

- app/assets/javascripts/dashboard.js
- app/models/minion.rb
- app/views/setup/discovery.html.slim
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/views/setup/discovery.html.slim_spec.rb
Previously, all the nodes found were used to be part of the cluster.
Now, user needs to select which ones they want to be used for it.
See bsc#1042193
> Allow selection of nodes to bootstrap cluster

- app/assets/javascripts/dashboard.js
- app/controllers/application_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/setup_controller.rb
- app/views/dashboard/_polling.html.slim
- app/views/dashboard/index.html.slim
- app/views/dashboard/unassigned_nodes.html.slim
- app/views/setup/_polling.html.slim
- config/routes.rb
- spec/controllers/dashboard_controller_spec.rb
- spec/features/add_unassigned_nodes_feature_spec.rb
After the initial selection of the cluster (discovery page), new nodes can eventually come up and user might want to add them. This PR makes that available with a dedicated page similar to the discovery one.
> Add unassigned nodes after cluster bootstrap

- app/assets/javascripts/dashboard.js
- app/assets/stylesheets/pages/nodes_list.scss
- app/controllers/concerns/discovery.rb
- app/controllers/salt_controller.rb
- app/views/dashboard/_pending_nodes.html.slim
- app/views/dashboard/index.html.slim
- app/views/setup/discovery.html.slim
- config/routes.rb
- lib/velum/salt.rb
- spec/controllers/dashboard_controller_spec.rb
- spec/controllers/salt_controller_spec.rb
- spec/controllers/setup_controller_spec.rb
- spec/features/add_unassigned_nodes_feature_spec.rb
- spec/features/admin_node_update_feature_spec.rb
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/features/dashboard_feature_spec.rb
- spec/features/monitoring_feature_spec.rb
- spec/lib/velum/salt_spec.rb
- spec/support/utils.rb
- spec/vcr_cassettes/salt/accept_node.yml
- spec/vcr_cassettes/salt/fetch_pending_minions.yml
Turning off `auto_accept` for salt means we need
to have a mechanism to accept nodes on a node
by node basis into the cluster.
This adds a pending nodes table that will show
all nodes that have not had their key accepted in salt
yet.
Current Issues:
> bsc#1043592 Add support for accepting nodes

- app/assets/javascripts/dashboard.js
- app/controllers/updates_controller.rb
- app/models/minion.rb
- app/views/dashboard/_update_admin_modal.html.erb
- spec/controllers/updates_controller_spec.rb
- spec/features/admin_node_update_feature_spec.rb
After clicking "Reboot to update", fixed wrong button text and locked modal until admin node is rebooted.
bsc#1045380, bsc#1045730
> 'Reboot to update' after click behavior

- app/assets/javascripts/dashboard.js
- app/views/setup/_warn_minimum_nodes_modal.html.erb
- app/views/setup/discovery.html.slim
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/support/helpers.rb
The etcd configuration used in CaaSP 1.0 requires
three total nodes to be present in the cluster
(can be 1 master and two minions) - without this,
etcd does not elect a leader, and bootstrap will fail.
See bsc#1040477
Until 2 nodes and 1 master is selected:
* Bootstrap cluster button disabled
* Warning message always displayed 
* Warning message gone when at least 2 nodes and 1 master is selected
If only 1 node and 1 master is selected:
* Bootstrap cluster enabled
* Warning message still being displayed
If user clicks on Boostrap cluster button while only 1 node and 1 master is selected:
* Warning modal is displayed
Previous discussion happened at https://github.com/kubic-project/velum/pull/183.
> Warn minimum nodes to bootstrap cluster

- app/assets/javascripts/setup.js
- app/controllers/dashboard_controller.rb
- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/views/dashboard/autoyast.xml.erb
- app/views/setup/welcome.html.slim
- spec/controllers/setup_controller_spec.rb
- spec/models/pillar_spec.rb
- spec/views/dashboard/autoyast.xml.slim_spec.rb
- spec/views/dashboard/index.html.slim_spec.rb
This pull request completes the work around handling proxy settings from velum.
It implements missing features like:
* Handle the `proxy:systemwide` pillar that was introduced by [this](https://github.com/kubic-project/salt/pull/107) pull request inside of the salt repository.
* Handle proxy settings inside of AutoYaST, fixing [bsc#1043538](https://bugzilla.suse.com/show_bug.cgi?id=1043538).
It also fixes previously uncovered bugs:
* Not being able to unset certain pillars from velum (see [this](https://github.com/kubic-project/velum/commit/1e877bafc44a00b3c301e511e4b868dc5c20524a) specific commit).
Finally it changes the UI to allow an easy way to enable/disable proxy settings. See the video below:
> Complete proxy support [bsc#1043538]

- app/assets/javascripts/dashboard.js
Helps the user to understand what he has to do to enable `Bootstrap cluster` button.
Code doesn't look good but strings builds like that are always ugly. Ideas are more than welcome.
> ux/ui: added title to bootstrap button

- .rubocop.yml
- spec/features/add_unassigned_nodes_feature_spec.rb
- spec/features/admin_node_update_feature_spec.rb
- spec/features/auth/login_feature_spec.rb
- spec/features/auth/signup_feature_spec.rb
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/features/dashboard_feature_spec.rb
- spec/features/monitoring_feature_spec.rb
- spec/support/helpers.rb
This fixes up some of the feature specs use of Capybara, and also fixes a number of incidences where the specs weren't actually doing anything since
expect do
end
won't actually evaluate the block being passed to expect without calling .to/.not_to ...  at the end
The specs currently fail, but they're failing in master at the moment too.
> fix up feature spec use of Capybara

- config/puma.rb
Puma allows you to restart the server based on the `mtime` of a file
`tmp/restart.txt`. We won't be using this functionality as the server
runs in a container and we have other means for restarting it.
This makes e2e-tests stable again.
> Remove `restart.txt` puma functionality

- .travis.yml
This file might have valuable content to identify a flaky test or
any other problem.
**Currently forcing failure to test**
> WIP: Print `log/test.log` upon failure in Travis

- .travis.yml
- spec/spec_helper.rb
When we find a flaky test, the fail fast version will contain relevant information
on the tail of the `test.log` fail, while the regular run will continue to show
any other errors.
> Add two runs for each ruby version, one with fail fast, the other a regular one

- .rubocop.yml
- bin/httpsd.rb
- bin/init
Ensure the "db is not yet ready" is served over https too. This fixes bsc#1047203.
The fix has been tested with devenv. Everything works fine until velum comes up, then velum will be served over port 3000 but with tls disabled (this is fixed by https://github.com/kubic-project/caasp-devenv/pull/23).
> Serve "db is not ready" static page over https [bsc#1047203]

- app/models/salt_event.rb
- app/models/salt_handler/minion_start.rb
- db/migrate/20170710081011_add_processed_at_worker_id_taken_at_indexes_to_salt_events.rb
- db/schema.rb
Fix some slow queries that we were having due to missing indexes.
Increase batch job size.
Fixes: bsc#1046862
> Add missing indexes for `salt_events` table

- app/assets/javascripts/dashboard.js
- app/views/dashboard/_pending_nodes.html.slim
After user accepts one or more nodes, 'Accept Node' link
is replaced by 'Acceptance in progress' text. The specific
minion is marked in `sessionStorage` and even if the user
refreshes the page, the 'Accept Node' won't appear until
it gets accepted.
> bsc#1046663: added indicator when user accepts node

- app/controllers/application_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/health_controller.rb
Not all redirections to `https` were properly handled. By making this
change we manually redirect to `https` as a `before_action` as before,
but handling a `redirect_to` in the chain (effectively stopping the
chain and in the expected order).
The reason behind this is that `force_ssl` called from our own filter:
https://github.com/rails/rails/blob/03925dc26a747075ff37660d1f0a060a8178bf66/actionpack/lib/action_controller/metal/force_ssl.rb#L62-L68
installs a `before_action`, but it's already too late for that very
request (we are already in the `before_actions` for that request).
Also, with the current implementation the filter gets installed after
our other `before_action` filters, what implies that the redirection
to `https` is not the very first filter in the chain, as it should
be.
By …
> `force_ssl` is documented to be executed from the class context

- app/models/salt_handler/bootstrap_orchestration.rb
- spec/models/salt_event_spec.rb
- spec/models/salt_handler/bootstrap_orchestration_spec.rb
We usually run the orchestrations manually as:
`salt-run state.orchestrate orch.kubernetes`
And this case was detected properly. This change adds support for also
detecting the orchestration result when the orchestration is called using
the `salt-api` on Velum (the general case):
`salt-run state.orchestrate mods=orch.kubernetes`
With this change we support both return results.
> Detect orchestration results when `mods` has been provided as argument

- app/models/salt_event.rb
- app/models/salt_handler/minion_orchestration.rb
- spec/models/salt_event_spec.rb
- spec/models/salt_handler/minion_orchestration_spec.rb
Handle the failure of an update orchestration in the same way we handle
a failure for a bootstrap orchestration.
bsc#1047895
> Handle failures of the update orchestration

- app/models/salt_event.rb
- app/models/salt_handler/minion_orchestration.rb
- spec/models/salt_event_spec.rb
- spec/models/salt_handler/minion_orchestration_spec.rb
Handle the failure of an update orchestration in the same way we handle
a failure for a bootstrap orchestration.
bsc#1047895
BP of https://github.com/kubic-project/velum/pull/249
> Handle failues of the update orchestration

- config/puma.rb
this allows for more concurrent api requests
a worker spawns a copy of the velum process
depending on how much RAM is used by velum, a second process (worker) will consume more RAM as well, so we might need to adapt the recommendation for the admin node (although i think it shouldn't matter much as a `puma` process has around 168MB with 2 workers)
> increase workers (bsc#1048533)

- app/assets/javascripts/dashboard.js
- spec/features/dashboard_feature_spec.rb
`Update all nodes` link should be shown if all nodes are in applied
state and there's an update available/retryable. If for some reason a node
goes to a different state than "applied" or there's no update,
link becomes unavailable.
> bsc#1045734: fix show/hide update link based on update/highstate

- app/assets/javascripts/dashboard.js
- spec/features/dashboard_feature_spec.rb
> bsc#1049165 : avoid orchestration action from ui while updating/adding node

- app/assets/javascripts/dashboard.js
- spec/features/dashboard_feature_spec.rb
`Update all nodes` link should be shown if all nodes are in applied
state and there's an update available/retryable. If for some reason
a node goes to a different state than "applied" or there's no update,
link becomes unavailable.
PR against master: https://github.com/kubic-project/velum/pull/261
> Backbport for bsc#1045734

- app/views/setup/welcome.html.slim
There is a typo in the pre-configured proxy exceptions during initial config: 127.0.01 instead of 127.0.0.1.  Note the missing dot.
> Fix loopback IP for proxy exception during initial configuration

- config/initializers/session_store.rb
(cherry picked from commit 2386314e2a1d3a99cc285366441311746303ab56)
backport of https://github.com/kubic-project/velum/pull/274
> [1.0] set secure flag in cookie (bsc#1050484)

- config/database.yml
Allow to specify a custom database name using the `VELUM_DB_NAME` environment variable.
The code falls back to the old value when the environment variable is not set.
This is needed to solve some issues with the new CI system.
> Set database name via environment variable

- config/database.yml
Allow to specify a custom database name using the `VELUM_DB_NAME` environment
variable.
The code falls back to the old value when the environment variable is not set.
This is a backport of https://github.com/kubic-project/velum/pull/283
> [1.0] Set database name via environment variable

- app/assets/javascripts/dashboard.js
- app/controllers/application_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/setup_controller.rb
- app/models/minion.rb
- app/models/pillar.rb
- app/views/setup/bootstrap.html.slim
- app/views/setup/discovery.html.slim
- app/views/setup/welcome.html.slim
- config/routes.rb
- lib/velum/salt.rb
- lib/velum/salt_minion.rb
- spec/controllers/dashboard_controller_spec.rb
- spec/controllers/setup_controller_spec.rb
- spec/controllers/updates_controller_spec.rb
- spec/features/add_unassigned_nodes_feature_spec.rb
- spec/features/admin_node_update_feature_spec.rb
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/features/dashboard_feature_spec.rb
- spec/features/monitoring_feature_spec.rb
- spec/lib/velum/salt_minion_spec.rb
- spec/models/minion_spec.rb
- spec/support/utils.rb
- spec/vcr_cassettes/salt/assign_role_to_minion.yml
- spec/vcr_cassettes/salt/bootstrap.yml
- spec/views/setup/discovery.html.slim_spec.rb
Velum will now have a new setup step after the roles have been chosen,
with the selected master as the kubernetes external FQDN name that will
contain its FQDN by default, allowing the customer to modify it to fit
their needs.
Fixes: bsc#1047284
> Modify Velum workflow for Kubernetes external FQDN name

- packaging/suse/velum.spec.in
openSUSE Factory review bot is declining requests because of that
> packaging: mention velum-rpmlintrc in the sources

- .travis.yml
(cherry picked from commit 5e20ff5730e7f6a9d195f16c294500872f95caa3)
backport of https://github.com/kubic-project/velum/pull/297
> [1.0] fix travis for mysql-devel

- app/assets/javascripts/dashboard.js
- app/views/dashboard/_pending_nodes.html.slim
The 'Accept All Nodes' button had the class '.accept-minion' that
is used to accept individually a node. When clicking on it the wrong
event listener callback was being called instead of the correct one.
Now it calls the expected event listener callback and makes the request
passing the expected arguments for all the nodes to be accepted.
For some reason I'm not aware, even not passing `minion_id` Salt was still able to accept all minions.
> Fixed 'Accept All Nodes' button ajax request

- app/assets/javascripts/setup.js
- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/views/setup/welcome.html.slim
- db/migrate/20170911102046_add_missing_container_networking_pillars.rb
* Add to the pillar the old settings. This migration will only be executed
on existing installations (as the `schema.rb` defines the up to date version and
this last migration will be excluded)
> Add networking settings to the setup UI

- app/controllers/setup_controller.rb
- app/models/pillar.rb
Before this change the last step of the setup would remove the pillar
information for the first step proxy values (since they were not
protected pillars).
Instead, explicitly say what unprotected pillars there are in each step
and allow the controller to override them with blank if they were provided
blank after having some other value.
> Only override blank pillars on the page they are shown

- app/controllers/setup_controller.rb
- app/views/setup/welcome.html.slim
- spec/controllers/setup_controller_spec.rb
After the first step of setting up the proxy settings,
when the user goes back to that initial page, the proxy
settings were lost. This can not only confuse the user
but also introduce undesired changes.
With this fix it doesn't happen anymore.
Fixes #300
> Fixed proxy settings when revisiting the page

- app/controllers/dashboard_controller.rb
- app/views/dashboard/autoyast.xml.erb
- lib/velum/suse_connect.rb
- spec/controllers/dashboard_controller_spec.rb
The service unavailable http error code (503) will only be returned now
until the first page of the setup is completed (so we have the dashboard
address to serve the autoyast profile).
When one of the following exceptions happens:
- Missing registration code
- Missing credentials for SCC/SMT
- Any HTTP error while connecting to SCC/SMT
We will still serve the autoyast content with a comment explaining why
the system cannot be registered. The returned http error code will be
success (200), but the XML will contain a comment stating why the system
cannot be registered.
Fixes: bsc#1049948
> Serve the autoyast content even when a SCC/SMT connection error happens

- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/models/user.rb
- config/ldap.yml
- lib/velum/ldap.rb
- spec/features/auth/ldap/ldap_integration_feature_spec.rb
Passes the LDAP parameters into the pillar so Dex can be bootstrapped
properly
> LDAP - remove hardcoded bind password

- app/models/pillar.rb
- app/views/setup/bootstrap.html.slim
This reverts commit f329dd7969f1ad7635b9e297b838e447fff3faa8.
Removal needed until tiller images are added back.
> Revert "Adding option to install Tiller"

- .travis.yml
- README.md
- app/views/devise/registrations/new.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/authentication.html.slim
- app/views/setup/_warn_minimum_nodes_modal.html.erb
- app/views/setup/discovery.html.slim
- app/views/setup/welcome.html.slim
- app/views/setup/worker_bootstrap.html.slim
- app/views/shared/_header.html.slim
- public/503_database_not_ready.html
- spec/lib/velum/suse_connect_spec.rb
- SUSE CaaSP
- SUSE Container as a Service Platform
both should be SUSE CaaS Platform.
Fixes: bsc#1058720
> Consistent naming of the product

- app/controllers/dashboard_controller.rb
- app/views/dashboard/autoyast.xml.erb
- lib/velum/suse_connect.rb
- spec/controllers/dashboard_controller_spec.rb
Revert https://github.com/kubic-project/velum/pull/270 partially, so we still support the air-gapped installations (bsc#1049948)
Fixes: bsc#1058999
> Remove warnings from within autoyast installation

- app/controllers/setup_controller.rb
This will only be effective on new installations, where the default pillar
value matches this value. Let's keep things simple and only override what
is in the UI or what will/can be different between versions.
> Do not add an override that will have the same value as the overriden one

- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/views/setup/bootstrap.html.slim
- app/views/setup/welcome.html.slim
Adding back the optional checkbox to install Tiller, Helm's server
component.
> Re-adding option to install Tiller

- app/assets/javascripts/dashboard.js
- app/views/setup/discovery.html.slim
- spec/features/bootstrap_cluster_feature_spec.rb
The title message for the 'Next' button on the nodes selection
page were out of date and weren't helping the user understand
what was wrong.
For each rule we use to validate the 'Next' button we
are adding a dedicated message to show to the user. This way
the user will know exactly what's wrong with the cluster
configuration.
I also fixed the "minimum of three nodes" alert to only be displayed
if the user didn't select 3 nodes (dones't matter if master was not
selected). The previous behavior was making it display if the
configuration wasn't supported even having 4 nodes selected. This
info now goes on the 'Next' button title message.
See bsc#1058915
(cherry picked from commit 1df8e6e761774863297544eb9d4ee33c0f99b2c7)
> ux: improved messages for 'Next' button on nodes selection

- app/assets/images/logo.svg
- app/assets/stylesheets/velum_general.scss
- app/views/shared/_header.html.slim
with the full name SUSE® CaaS Platform
bsc#1062247
also the login page and the normal layout header will use the svg
~~there is only still one issue that the navbar in the app and in the login don't share the same css it seems, i have tweaked the image size in the application css but maybe that;'s not the best way to do it. @vitoravelino do you have an idea?~~
updated to `height: 60px` as per @vitoravelino's suggestion
> bsc#1062247 add new svg logo

- app/models/salt_handler/minion_highstate.rb
- app/models/salt_handler/minion_orchestration.rb
- spec/models/salt_handler/minion_highstate_spec.rb
- spec/models/salt_handler/minion_orchestration_spec.rb
We are marking success depending on highstates, what makes a bit misleading
for the overall orchestration process. At this moment, orchestration will wait
for some tasks to have been completed (like some `kubectl apply` commands, which
apply immediately). We aren't waiting for the global orchestration result, and
this means that all minions might be marked as successful when we haven't really
waited for the overall orchestration to have finished.
This can have important implications, like not waiting for Dex to be completely
ready while the orchestration is waiting for it.
We just mark failed highstates as an early failure, but wait for the orchestration
result to finish and be succesful in order to mark pending nodes as successful.
This will also align with the current restritions in the …
> Wait for orchestration result for marking success on minions

- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/views/setup/bootstrap.html.slim
- app/views/setup/welcome.html.slim
This should be used by Dex to redirect back to Velum, allowing for scenarios
where the admin node's private IP is not accessible to the outside world - e.g.
as is the case on OpenStack and possibly other cloud environments.
Part of bsc#1062291
Depends-On: https://github.com/kubic-project/salt/pull/251
Depends-On: https://github.com/kubic-project/automation/pull/164
> Collect the dashboard hosts external FQDN

- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/views/setup/bootstrap.html.slim
- app/views/setup/welcome.html.slim
This should be used by Dex to redirect back to Velum, allowing for scenarios
where the admin node's private IP is not accessible to the outside world - e.g.
as is the case on OpenStack and possibly other cloud environments.
Part of bsc#1062291
Backport of https://github.com/kubic-project/velum/pull/322
> [2.0] Collect the dashboard hosts external FQDN

- config/environments/production.rb
the logo has recently changed to svg and needs to be compiled too
otherwise it wont be shown
bsc#1062878
(cherry picked from commit d871bacd098019cf2522804453af8958d325274b)
> [2.0] also compile svg

- app/controllers/application_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/oidc_controller.rb
- spec/controllers/oidc_controller_spec.rb
a url_for renders a url with from wherever you have requested from
make sure to include the known dashboard url in the redirect_url
otherwise dex will render a Bad Request as it doesn't know the
dns entry
bsc#1062728
> bsc#1062728: correctly render redirect_url

- app/models/salt_handler/minion_orchestration.rb
Consider all pending and failed minions when we receive a kubernetes
orchestration result. If later orchestrations succeed they should also
mark failed nodes as succeeded.
Fixes: bsc#1064281
> When an orchestration result is received, update failed nodes too

- .gitignore
- spec/spec_helper.rb
this has the big advantage that you can check the results directly
in velum under http(s)://$velum/coverage/index.html
since we switched the official devenv to containers within VM's the
folder is not accessible that easy anymore
> spec: make coverage folder public (in development)

- app/models/salt_handler/minion_orchestration.rb
Consider all pending and failed minions when we receive a kubernetes
orchestration result. If later orchestrations succeed they should also
mark failed nodes as succeeded.
Fixes: bsc#1064281
Backport of https://github.com/kubic-project/velum/pull/350
> [2.0] When an orchestration result is received, update failed nodes too

- app/assets/javascripts/dashboard.js
- app/assets/stylesheets/authentication.scss
- app/assets/stylesheets/components/notifications.scss
- app/views/shared/_notification.html.slim
- app/views/shared/_notifications.html.slim
We are regenerating Velum's certificate by adding the external
dashboard fqdn/ip to the Velum certificate. For this certificate
to be reloaded we are currently doing a `docker restart` on Velum
while the orchestration is being executed.
This has a bad effect on the user session as he/she is waiting
for the polling to finish. Without them noticing, the polling will
start failing as the certificate changed under them, and they need
to accept it, but ajax requests will just fail because of this.
With this patch we are notifying the user that the browser cannot
connect with Velum API and suggests he/she to try to reload the session.
Fixes bsc#1064641
> Notify user when not able to fetch data from Velum API

- app/assets/javascripts/dashboard.js
- app/assets/stylesheets/authentication.scss
- app/assets/stylesheets/components/notifications.scss
- app/views/shared/_notification.html.slim
- app/views/shared/_notifications.html.slim
We are regenerating Velum's certificate by adding the external
dashboard fqdn/ip to the Velum certificate. For this certificate
to be reloaded we are currently doing a `docker restart` on Velum
while the orchestration is being executed.
This has a bad effect on the user session as he/she is waiting
for the polling to finish. Without them noticing, the polling will
start failing as the certificate changed under them, and they need
to accept it, but ajax requests will just fail because of this.
With this patch we are notifying the user that the browser cannot
connect with Velum API and suggests he/she to try to reload the session.
Fixes bsc#1064641
(cherry picked from commit d531ee3fa4c883edee9163e9be5452dccc8bbf4c)
> [2.0] Notify user when not able to fetch data from Velum API

- app/models/minion.rb
- app/views/dashboard/_pending_nodes.html.slim
- app/views/setup/discovery.html.slim
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/models/minion_spec.rb
If we are setting the role locally only (on the database), set the
minion status to `not_applied`. If we are also setting the remote role
(set on salt too), set the minion status to `pending`.
Since there's no Orchestration model yet, there's no entity to control
this assignments, and Minion model will set one or the other depending
on the `remote` attribute of `assign_role`.
Fixes: bsc#1063977
> When roles are set, set `not_applied` if it's a local assignment.

- app/models/minion.rb
- app/views/dashboard/_pending_nodes.html.slim
- app/views/setup/discovery.html.slim
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/models/minion_spec.rb
If we are setting the role locally only (on the database), set the
minion status to `not_applied`. If we are also setting the remote role
(set on salt too), set the minion status to `pending`.
Since there's no Orchestration model yet, there's no entity to control
this assignments, and Minion model will set one or the other depending
on the `remote` attribute of `assign_role`.
Fixes: bsc#1063977
> [2.0] When roles are set, set `not_applied` if it's a local assignment.

- app/assets/javascripts/dashboard.js
otherwise the user is left without any clue what to do
@vitoravelino could you please have a look if this makes sense, or if it can be done better?
@kiall @ereslibre would it be easy to get the error(s) of the orchestration to be more specific in the flash message what happened? i believe it might be not that trivial to filter the responsible error and then condense it in a message that fits into a flash message...
> alert the user when bootstrap failed

- app/views/setup/welcome.html.slim
Small typo on "Overlay network settings" settings.
Fixes bsc#1065265
> typo: interally -> internally

- app/views/shared/_notifications.html.slim
This is an attempt to make the experience better. We thought that
the previous message was too aggressive. Since this message will
always be shown for 2.0 at least, we want to tranquilize the user
that it's an expected behavior.
> Improved failure alert message

- app/views/setup/welcome.html.slim
Small typo on "Overlay network settings" settings.
Fixes bsc#1065265
(cherry picked from commit a30a9dfba017b2023fb4b8716a895f809dd0770f)
> [2.0] typo: interally -> internally

- app/views/oidc/done.html.slim
- app/views/shared/_header.html.slim
Also, add a link to the `root_path` on the icon of CaaS Platform.
Fixes: bsc#1062728
Backport of https://github.com/kubic-project/velum/pull/365
> Add kubeconfig tips on the download page

- app/models/user.rb
- lib/tasks/velum.rake
In 1.0 user login information was stored in the database whereas in 2.0
this information resides in LDAP.
Fixes: bsc#1065450
> Add `velum:migrate_users` task that will migrate database-backed users into LDAP-backed users

- app/assets/javascripts/dashboard.js
otherwise the user is left without any clue what to do
(cherry picked from commit 3151ad8a56c1d5126efe5c87f11037c045f4b26e)
Backport https://github.com/kubic-project/velum/pull/352
> [2.0] alert the user when bootstrap failed

- app/views/shared/_notifications.html.slim
This is an attempt to make the experience better. We thought that
the previous message was too aggressive. Since this message will
always be shown for 2.0 at least, we want to tranquilize the user
that it's an expected behavior.
(cherry picked from commit 758d9f597f3453a8dd8a215d62b344f2cb548cd5)
Backport of https://github.com/kubic-project/velum/pull/356
> [2.0] Improved failure alert message

- app/assets/javascripts/dashboard.js
Moved the calls of `toggleMinimumNodesAlert` and
`handleBootstrapErrors` to be done after the checkbox
changes to `true` instead of by any change (false/true).
With this change there will be no middle state that cause
the alert when `toggleMinimumNodesAlert` is called.
Fixes bsc#1066371
(cherry picked from commit dc92f64c03e739cb20c474ca5c74fe495fecc610)
Backport of #374
> [2.0] js: fixed undesired minimum nodes alert blink

- app/assets/javascripts/dashboard.js
Moved the calls of `toggleMinimumNodesAlert` and
`handleBootstrapErrors` to be done after the checkbox
changes to `true` instead of by any change (false/true).
With this change there will be no middle state that cause
the alert when `toggleMinimumNodesAlert` is called.
Fixes bsc#1066371
> js: fixed undesired minimum nodes alert blink

- app/assets/javascripts/dashboard.js
Changed from green to gray. The reason behind this is that green
is usually associated with a success operation and gray is a
more neutral color that doesn't add much meaning.
This change was a quick suggestion from Cynthia when I showed her Velum.
> ux: changed color of pending status icon

- config/database.yml
Test and production database names are fixed.
> Only allow `development` environment to override the database with `VELUM_DB_ENV`

- app/views/oidc/done.html.slim
If we forced the location directly, javascript assets were never loaded
as their loading are interrupted by the browser because of the `href` change.
This ensures we first load all the assets (so delete, put, patch links work
through jquery as usual), and then we force the redirection to happen.
Fixes: bsc#1066611
> When we are back in Velum from Dex, allow for assets to be loaded

- Gemfile.lock
this includes a fix for lockup off ssl connections
> update puma to 3.10.0

- app/assets/javascripts/alert.js
- app/assets/javascripts/dashboard.js
- app/views/layouts/application.html.slim
- app/views/shared/_notification.html.slim
- app/views/shared/_notifications.html.slim
The alert notifying the user that the bootstrap has failed was
overriding the type of any previous alert that were on the page.
This was causing some confusing to some users.
Now it creates an alert everytime we check if there's a failed
bootstrapped node without interfering other alerts.
Also removed unnecessary stuff from the notification partial.
Fixes bsc#1069258
> js: fixed alert color being overridden

- app/controllers/setup_controller.rb
There's no possible use case for these pillars in which they were
filled with information and then the customer will clear them (as they
are required).
Keep things as simple as possible until we refactor this part.
Without this change, a specially crafted HTTP request could be made to
remove the content of those pillar values, when this is not ideal.
> Remove unneeded unprotected pillars

- Gemfile.lock
it must have accidentally be gotten updated via #390
rubocops Gemfile suggests gem 'rake', '~> 12.0' at this
point in time so we can safely stick to 12.0.0
https://github.com/bbatsov/rubocop/blob/082408/Gemfile#L9
> downgrade rake again

- app/controllers/oidc_controller.rb
This was needed to workaround capybara + poltergeist being unable to download
files, this workarond is now down in the velum-interactions tooling, rather than
in a shiped part of the codebase.
Depends-On: https://github.com/kubic-project/automation/pull/198
> Remove dev vs prod kubeconfig download difference

- app/controllers/internal_api/v1/pillars_controller.rb
- spec/controllers/internal_api/v1/pillars_controller_spec.rb
This gives a chance for default salt pillars to be used.
> Reject `nil` values on the Velum pillar.

- app/assets/javascripts/alert.js
- app/assets/javascripts/dashboard.js
- app/views/layouts/application.html.slim
- app/views/shared/_notification.html.slim
- app/views/shared/_notifications.html.slim
The alert notifying the user that the bootstrap has failed was
overriding the type of any previous alert that were on the page.
This was causing some confusing to some users.
Now it creates an alert everytime we check if there's a failed
bootstrapped node without interfering other alerts.
Also removed unnecessary stuff from the notification partial.
Fixes bsc#1069258
(cherry picked from commit d63fba6cd8204238893b90bacd4d1eeceec61655)
Backport of #383
> [2.0] js: fixed alert color being overridden

- app/views/dashboard/autoyast.xml.erb
Disables the creation of the swap partition on the nodes provisioned by AutoYaST.
This fixes bsc#1075001.
This is a simple rebase of PR https://github.com/kubic-project/velum/pull/194. I tested it and it works fine.
> AutoYaST: disable creation of swap [bsc#1043813]

- db/migrate/20180109145421_set_udp_as_default_flannel_backend.rb
- db/schema.rb
This migration will only be executed on old installations, while on new ones
(where we will use the default salt pillar value) this migration won't be
run, so there won't be a pillar override.
Depends on: https://github.com/kubic-project/salt/pull/201
> [CNI] Set default flannel backend to UDP for old installations

- app/controllers/application_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/oidc_controller.rb
Also, do not repeat the allowed hosts if they match.
Fixes: bsc#1071500
Backport of https://github.com/kubic-project/velum/pull/354
> Reuse filter logic for known hosts.

- config/data/azure-types.json
- config/data/ec2-types.json
- config/data/gce-types.json
- lib/velum/instance_type.rb
- spec/lib/velum/instance_type_spec.rb
In order to present a reasonable set of choices for instance_type, acollection of instance types was hand-picked for each supported public cloud framework.
These will be presented in the bootstrap UI, based on design feedback from the SUSE UI/UX team.
> Consistent representation of public cloud instance types

- db/migrate/20180118103201_change_pillar_value_to_text.rb
- db/schema.rb
This migration changes the pillar `value` column from `string` to `text` so we keep in sync with the 2.0 branch where we need this column to allow bigger contents (to store certificates, for example).
> Add migration to change the pillar value column to text

- packaging/suse/make_spec.sh
in tumbleweed it's named mariadb, in sle it's mysql
> adapt devel libraries to tumbleweed

- app/models/salt_handler/minion_highstate.rb
- app/models/salt_handler/orchestration_result.rb
- spec/models/salt_handler/orchestration_result_spec.rb
When detecting highstate success as well as orchestration success we
are checking the result success status and also checking that the
global `retcode` is 0. This latest check is not strictly necessary and
under certain conditions it is not desirable.
> Do not require `retcode` to be 0 to detect success.

- packaging/suse/make_spec.sh
a bundler BuildRequire is already hardcoded
other than that it prevents a false strict dependency on bundler, e.g.
if i run make_spec.sh on openSUSE 42.1 it will render bundler 1.10.6
whatever is installed on the system. this happened in our concourse
build container that uses 42.1 as a base system
Follow up of https://github.com/kubic-project/velum/pull/428
> skip bundler during spec file creation

- packaging/suse/velum.spec.in
`bundle clean` also removes stale executables under `bin`. It is fine that
bundler thinks that `bundler` executable is stale, but it's not, we are just
installing it as a separate gem, so do that at the end of the spec, after
we have executed `bundle clean`.
> Install `bundler` after `bundle clean`.

- app/assets/javascripts/dashboard/dashboard.js
- app/controllers/dashboard_controller.rb
- app/views/dashboard/unassigned_nodes.html.slim
- spec/features/add_unassigned_nodes_feature_spec.rb
- spec/features/bootstrap_cluster_feature_spec.rb
Velum now validates if selected nodes to bootstrap and be added to the cluster
have unique hostnames. The error message appears in an error alert.
> js: added unique hostnames validation

- app/views/oidc/done.html.slim
This allows a user to proceed, even if the JS redirect does not execute.
> Add fallback link to fetch kubeconfig if redirect fails

- lib/velum/salt_api.rb
HAProxy has a 50 sec timeout, meaning HAProxy will kill the connection before Velum times out waiting for salt-api when there are issues.
> Reduce salt-api timeout from 60 sec, to 30 sec

- .codeclimate.yml
this is one example of overlapping checks that are performed
by rubocop and therefore can be disabled, otherwise it shows
up on the github status always
> disable codeclimate check that rubocop already does

- app/views/dashboard/index.html.slim
I didn't refactor down the line because ultimately we cannot have an
enum with a :update status (rails will complain, so at least the enum
on the Orchestration model would need to be called :upgrade).
For that reason, keep everything as it is (call internally `upgrade`,
but just show "Retry cluster update" on the button label).
> Be consistent and rename `upgrade` to `update`.

- db/seeds.rb
This currently fails, as the method does not exist:
NoMethodError: undefined method `find_or_initialize' for #<ActiveRecord::Relation []>
> Fix db/seeds creation of SUSE registry URL record

- app/controllers/internal_api/v1/pillars_controller.rb
- spec/controllers/internal_api/v1/pillars_controller_spec.rb
Without this change `cloud:provider` won't be saved in Salt as pillar.
> Add cloud:provider to cloud_provider_contents for Salt API call

- app/assets/javascripts/dashboard/dashboard.js
- spec/features/bootstrap_cluster_feature_spec.rb
This is a follow-up of 8017753. After QA, this fixes an issue and
improves the workflow of accepting pending nodes.
> js: improved hostnames validation and workflow

- app/assets/javascripts/dashboard/dashboard.js
- app/controllers/dashboard_controller.rb
- app/views/dashboard/unassigned_nodes.html.slim
- spec/features/add_unassigned_nodes_feature_spec.rb
So far we only allowed workers to be added to the cluster through the
unassigned nodes page.
With this patch, we are now allowing the users to select the roles of the
nodes they want to add to the cluster. Very similar to what is available
from the discovery bootstrap page.
This feature keep forcing the user to respect the contrainst of having an
odd number of master nodes so we have a stable topology.
feature#add_master_node
> ui: allowed master node to be added to the cluster

- app/assets/javascripts/setup/setup.js
- app/assets/stylesheets/components/panels.scss
- app/assets/stylesheets/pages/settings.scss
- app/controllers/setup_controller.rb
- app/helpers/setup_helper.rb
- app/models/pillar.rb
- app/views/setup/cloud/_openstack_configuration.html.slim
- app/views/setup/cloud/_settings.html.slim
- spec/controllers/setup_controller_spec.rb
- spec/features/bootstrap_settings_feature_spec.rb
- spec/helpers/setup_helper_spec.rb
If a cloud framework is previously set, CPI value, if enabled, would be
based on what was set.
For example, if cloud:framework pillar value is "ec2", we would
set "ec2" as the CPI value if enabled. The same be applied for GCE and
Azure.
Otherwise, "openstack" would be the default value for CPI if enabled.
> Improved CPI behavior with cloud frameworks

- bin/init
- lib/tasks/cpi.rake
This task can be called:
```
docker exec -it $(docker ps | grep "velum-dashboard" | awk '{print $1}') entrypoint.sh bash -c "export RAILS_ENV=production; bundle exec rake velum:cpi_openstack['/etc/caasp/openstack.conf']
```
Example `openstack.conf` file which can be inject by cloud-init
```
[Global]
auth-url="http://prvcld.caasp.suse.net:5000/v3"
username="test"
password="secure"
tenant-name="caasp"
domain-name="caasp"
region="az"
[LoadBalancer]
lb-version=v2
subnet-id="e4f92380-4189-4dab-84c9-82830fe45522"
floating-network-id="e4f92380-4189-4dab-84c9-82830fe43311"
create-monitor=yes
monitor-delay=1m
monitor-timeout=30s
monitor-max-retries=3
[BlockStorage]
trust-device-path=false
bs-version=v3
```
> Add rake task to import CPI options

- lib/velum/salt_api.rb
Allow enough time for the salt timeout, and a minion timeout before cutting off the API call.
Should resolve https://github.com/kubic-project/velum/issues/456 introduced in 6189bcad .
> Extend salt-api timeout as long as possible.

- app/assets/javascripts/dashboard/dashboard.js
- app/views/dashboard/_warn_node_removal_modal.html.slim
- spec/features/node_removal_feature_spec.rb
This is a follow up from the previous node removal feature patch that
shows the requirement of minimum of three nodes when user removes a
node.
enhancement#follow_up_node_removal
> Added minimum of three nodes to warning

- app/assets/javascripts/dashboard/dashboard.js
- app/views/dashboard/index.html.slim
- spec/features/dashboard_feature_spec.rb
Whenever the cluster goes to an unsupported configuration state, an
alert is shown with the reason to keep the user aware of that.
enhancement#unsupported_config_msg
> Added alert in overview page when unsupported config

- app/models/salt_handler/orchestration_result.rb
- app/models/salt_handler/orchestration_trigger.rb
- spec/models/salt_handler/orchestration_result_spec.rb
It's more correct for the removal orchestration to read the parameters that were
passed to the orchestration rather than to rely on the current status of the
minions on the database.
> Properly create and update orchestrations that have been executed out of Velum

- app/helpers/setup_helper.rb
- app/views/setup/cloud/_settings.html.slim
- spec/features/bootstrap_settings_feature_spec.rb
- spec/helpers/setup_helper_spec.rb
When no cloud:framework pillar is set, it means that CaaSP is not
running in a cloud environment. So it doesn't make sense to show that
option in that scenario.
feature#cpi
> Hide CPI panel when no cloud framework

- app/assets/javascripts/dashboard/dashboard.js
- spec/features/node_removal_feature_spec.rb
This patch fixes the warning modal that was being shown when the cluster
was in an unsupported configuration (even # masters) and user was trying
to remove a normal worker node. This scenario should trigger that
warning modal.
bsc#1087123
> Fixed # of masters warning when removing worker

- app/assets/javascripts/dashboard/dashboard.js
- spec/features/add_unassigned_nodes_feature_spec.rb
This patch fixes the warning that was being shown when the user selected
a new master node to be added and it wasn't breaking the odd number
constraint. Before this, the current assigned masters were not being
considered to show/not show the warning.
Now the warning will only be shown if the number of masters to be added
breaks the constraint as it's expected to be.
bsc#1087267
> Fixed # of masters warning when adding a new master

- app/assets/stylesheets/pages/instance_type.scss
- app/controllers/internal_api/v1/pillars_controller.rb
- app/controllers/setup_controller.rb
- app/models/cloud_cluster.rb
- app/models/pillar.rb
- app/views/setup/worker_bootstrap_azure.html.slim
- app/views/setup/worker_bootstrap_ec2.html.slim
- spec/controllers/internal_api/v1/pillars_controller_spec.rb
- spec/controllers/setup_controller_spec.rb
- spec/models/cloud_cluster_spec.rb
* An pillar for Azure storage account name was described as optional in the documentation, but in practice is required.
* Improve the layout of inputs in public cloud forms.
* Add an explanatory link on Azure service principal attributes.
> Public Cloud fixes

- app/models/salt_handler/minion_orchestration.rb
If we executed: `salt-run state.orchestrate 2` we get an error that crashes the event
processor:
`TypeError: no implicit conversion of String into Integer`
This happens because of `fun_args.first["mods"]` being `2["mods"]`, what makes it
crash with the previous exception. `2.respond_to?(:[])` is `true`, so I think the
best thing we can do here is to swallow the exception, and ignore the event if we
cannot even process its arguments.
Fixes: bsc#1088597
Backport from https://github.com/kubic-project/velum/pull/489
> [2.0] Avoid the event processor from crashing if it cannot interpret the event arguments

- app/models/salt_handler/orchestration.rb
If we executed: `salt-run state.orchestrate 2` we get an error that crashes the event
processor:
`TypeError: no implicit conversion of String into Integer`
This happens because of `fun_args.first["mods"]` being `2["mods"]`, what makes it
crash with the previous exception. `2.respond_to?(:[])` is `true`, so I think the
best thing we can do here is to swallow the exception, and ignore the event if we
cannot even process its arguments.
Fixes: bsc#1088597
> Avoid the event processor from crashing if it cannot interpret the event arguments

- app/models/salt_handler/minion_orchestration.rb
If we executed: `salt-run state.orchestrate 2` we get an error that crashes the event
processor:
`TypeError: no implicit conversion of String into Integer`
This happens because of `fun_args.first["mods"]` being `2["mods"]`, what makes it
crash with the previous exception. `2.respond_to?(:[])` is `true`, so I think the
best thing we can do here is to swallow the exception, and ignore the event if we
cannot even process its arguments.
Fixes: bsc#1088597
Backport of https://github.com/kubic-project/velum/pull/489
> [2.1] Avoid the event processor from crashing if it cannot interpret the event arguments

- bin/init
- lib/tasks/velum.rake
This is a generic rake task that will import seed pillar values from
all files in /etc/caasp/pillar-seeds/.
The format of files in this folder should match:
- pillar: cloud:framework
value: openstack
feature#hide-openstack-cpi
Related to https://github.com/kubic-project/caasp-container-manifests/pull/170
Related to https://build.suse.de/request/show/161767
> Add and run a import_pillar_seeds rake task

- lib/velum/salt_api.rb
Allow enough time for the salt timeout, and a minion timeout before cutting off the API call.
Backport of #444 + #468
> [2.1] Add salt-api timeout

- app/models/pillar.rb
Allow users to override the `kubernetes:feature_gates` pillar via our external pillar source.
Required by this PR https://github.com/kubic-project/salt/pull/467
> Support the kubernetes feature gates pillar

- app/assets/javascripts/setup/setup.js
- app/assets/stylesheets/components/panels.scss
- app/assets/stylesheets/pages/setup.scss
- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/views/setup/settings/_container_runtime.html.slim
- app/views/setup/welcome.html.slim
Allow the user to choose between different container runtimes.
This enables users to create clusters backed by cri-o instead of docker.
feature#crio
@ajaeger and @eotchi: can you provide advice on this PR, especially when it comes to the following points:
* wording: how I described what a container runtime is, what are the differences between cri-o and docker
* placement of the settings inside of the page: right now I placed that right at the bottom of the page
* should we make more prominent the fact cri-o is tech preview (eg: show a warning box when chosen)
By default `docker` is being used:
Nothing fancy to be shown, this is what happens when `cri-o` is chosen:
This is probably going to break openQA, ping @kravciak
> Bootstrap settings: cri-o support

- app/assets/javascripts/dashboard/dashboard.js
- app/assets/stylesheets/pages/nodes_list.scss
- app/views/dashboard/index.html.slim
- spec/features/node_force_removal_feature_spec.rb
- spec/features/node_removal_feature_spec.rb
'Remove' and 'Force remove' links were being shown at the same time so
far. But 'Force remove' only makes sense to be shown when a previous
removal has failed.
With this we are showing only one link at a time. When the highstate of
a minion is fine, we show 'Remove'. Whenever it comes 'removal_failed',
we show 'Force remove'.
enhancemente#node-removal
> node removal: improved way of showing removal links

- app/views/setup/discovery.html.slim
Small fix of a misleading text that referred to an old behavior of the
nodes discovery page.
bsc#1059787
(cherry picked from commit 9963ac7625c21fbe3bd609dbab791c9f8b9a9ab3)
> [2.1] Fixed misleading text about nodes selection

- app/views/setup/discovery.html.slim
Small fix of a misleading text that referred to an old behavior of the
nodes discovery page.
bsc#1059787
(cherry picked from commit 9963ac7625c21fbe3bd609dbab791c9f8b9a9ab3)
> [3.0] Fixed misleading text about nodes selection

- app/views/setup/discovery.html.slim
Small fix of a misleading text that referred to an old behavior of the
nodes discovery page.
bsc#1059787
> Fixed misleading text about nodes selection

- app/models/minion.rb
- spec/features/node_force_removal_feature_spec.rb
This will avoid strange issues when Rails caches the attributes of the `minions`
table (we also avoid the need to `reload` explicitly for this corner cases).
Fixes: bsc#1091843
> Use `update_columns` to update minion attributes with the minion reconciler

- app/models/minion.rb
- spec/features/node_force_removal_feature_spec.rb
This will avoid strange issues when Rails caches the attributes of the `minions`
table (we also avoid the need to `reload` explicitly for this corner cases).
Fixes: bsc#1091843
(cherry picked from commit 45bee1144bdcb9d42b4d7ca84bf5ff703032977e)
> [3.0] Use `update_columns` to update minion attributes with the minion reconciler

- bin/init
- bin/run
Do not make this script run the puma server. This way, this command
can be run as an init container, leaving the server execution to the
pod definition.
Fixes: bsc#1091843
(cherry picked from commit 1f3adaa64791b1caf11c95717517616a10fad811)
> [3.0] Make the `bin/init` process only do initialization operations

- bin/init
- bin/run
Do not make this script run the puma server. This way, this command
can be run as an init container, leaving the server execution to the
pod definition.
Fixes: bsc#1091843
Depends on: https://github.com/kubic-project/caasp-container-manifests/pull/176
Depends on: https://github.com/kubic-project/automation/pull/368
> Make the `bin/init` process only do initialization operations

- app/assets/javascripts/dashboard/dashboard.js
- app/controllers/concerns/discovery.rb
- app/controllers/setup_controller.rb
- app/models/cloud_cluster.rb
- app/models/salt_event.rb
- app/models/salt_handler/cloud_bootstrap.rb
- app/models/salt_job.rb
- app/views/setup/discovery.html.slim
- db/migrate/20180427014552_create_salt_jobs.rb
- db/schema.rb
- packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
- spec/controllers/setup_controller_spec.rb
- spec/factories/salt_job_factory.rb
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/models/cloud_cluster_spec.rb
- spec/models/salt_handler/cloud_bootstrap_spec.rb
- spec/models/salt_job_spec.rb
- spec/vcr_cassettes/salt/cloud_profile.yml
- spec/vcr_cassettes/salt/login_500.yml
After bootstrapping, on the discovery step, report the number of pending salt-cloud jobs, and any instances that failed to deploy.
Actual error messages cannot be fetched due to a failure in salt (see https://bugzilla.suse.com/show_bug.cgi?id=1087365 ), so we can only point at the logs for now.
*BONUS*: `setup/discovery` was performing a lot of work that's only used on JSON requests, and ignored on HTML requests; this caused measurable lag in rendering of `setup/discovery`.
> Salt-cloud feedback

- app/assets/javascripts/cloud/bootstrap.js
Since that actually triggered construction of nodes, we need just a little something to keep the impatient from clicking over & over.
> Prevent double-clicking setup#bootstrap submit in public cloud

- app/controllers/oidc_controller.rb
- app/views/oidc/done.html.slim
- app/views/oidc/kubeconfig.erb
This allows a user to proceed, even if the JS redirect does not execute.
Backport of https://github.com/kubic-project/velum/pull/427
Backport of https://github.com/kubic-project/velum/pull/441
> [2.1] Add fallback link to fetch kubeconfig if redirect fails

- app/assets/stylesheets/components/header.scss
- app/assets/stylesheets/velum_general.scss
- app/controllers/internal_api/v1/pillars_controller.rb
- app/controllers/settings/kubelet_compute_resources_reservations_controller.rb
- app/helpers/settings_helper.rb
- app/models/kubelet_compute_resources_reservation.rb
- app/views/layouts/application.html.slim
- app/views/layouts/settings.html.slim
- app/views/settings/_sidebar.html.slim
- app/views/settings/kubelet_compute_resources_reservations/_resources.html.slim
- app/views/settings/kubelet_compute_resources_reservations/index.html.slim
- config/routes.rb
- db/migrate/20180508070232_create_kubelet_compute_resources_reservations.rb
- db/schema.rb
- packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
- spec/controllers/internal_api/v1/pillars_controller_spec.rb
- spec/controllers/settings/kubelet_compute_resources_reservations_controller_spec.rb
- spec/factories/kubelet_compute_resources_reservation.rb
- spec/models/kubelet_compute_resources_reservation_spec.rb
Allow users to provide values for the kubelet compute resources reservations and hard eviction policies.
This is, together with https://github.com/kubic-project/salt/pull/518, fixes [bsc#1086185](https://bugzilla.suse.com/show_bug.cgi?id=1086185).
The pull request is composed by two commits:
* The first commit introduces all the pillars required by the feature and exposes them through the internal API of velum. This is mandatory to get the bug fix
* The second commit is a quick attempt at introducing a new UI to handle these parameters. I have quite some questions about the UI. These are complex tasks, I tried to rephrase what the [kubernetes official documentation](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources) says. However I'm looking for feedback, …
> Kubelet compute resources

- packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
it got wrongly rebased in #502
fix#patch
(cherry picked from commit 4ec7dbab1666f77a1b236a65e1d2e83b5f80bcb3)
backport of https://github.com/kubic-project/velum/pull/524
> [3.0] rebase patch

- app/controllers/updates_controller.rb
This ensures that when the admin is back, the status of the minion on
the database will match the grains from the very beginning, without
having to rely on the background task updating all minions (including
the admin) update status.
Fixes: bsc#1092910
(cherry picked from commit 95ecd9e3e7f72ab32aa7c7bdaece886e4163c80c)
> [3.0] Mark admin as updated when we are going to reboot it

- app/controllers/updates_controller.rb
This ensures that when the admin is back, the status of the minion on
the database will match the grains from the very beginning, without
having to rely on the background task updating all minions (including
the admin) update status.
Fixes: bsc#1092910
> Mark admin as updated when we are going to reboot it

- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/views/setup/welcome.html.slim
Starting with v3 we changed the default flannel backend from UDP to
VXLAN.
The VXLAN backend does not work when users have segmented networks,
while the UDP one does.
The salt states are already capable of switching between the two
backends, we just needed to expose the right pillars from Velum.
This commit changes the setup UI to allow users to choose the backend of
and the port used by flannel.
Mandatory screenshot
feature#flannel-backend
> Allow users to choose flannel's backend

- app/assets/stylesheets/velum_bootstrap-variables.sass
- app/views/settings/_apply.html.slim
the warning that any changes are not immediately applied should be
more visible
a blue flash message background with a blue button is not visible
enough
settings-ui#apply
> emphasize settings apply workflow

- app/views/settings/registries/_form.html.slim
Fixes incorrect redirect: when cancelling an edit to a `registry`, it redirected to the `registry_mirror` list.
> Redirect to registry page instead of mirror when editing a registry.

- app/models/pillar.rb
Make Velum aware of some pillars related with CNI/cilium. That makes
possible to switch to cilium.
No UI is needed for that right now.
feature#cilium-selected-preview-on-v3
> Allow override of CNI related pillars

- app/assets/javascripts/dashboard/dashboard.js
- spec/features/bootstrap_cluster_feature_spec.rb
We are storing the minion id in session storage while it goes under
pending acceptance state. However we were not handling its removal if
the acceptance succeeded or if an error happened after the request.
This patch fixes those scenarios avoiding unwanted user experiences.
bsc#1093869
> js: removal of pending acceptance state

- app/helpers/application_helper.rb
- app/views/dashboard/index.html.slim
- app/views/devise/sessions/new.html.slim
- config/routes.rb
Some people that are not the admin user need the kubectl config file.
This link is only accessible in the dashboard page.
This patch shows s a link on for anonymous users on the authentication
page.
bsc#1093528
(cherry picked from commit 53124228fc1ad3ab570aa4be353a1fc1f6b1cd8d)
> ui: show kubectl config download link on auth page

- app/assets/javascripts/dashboard/dashboard.js
Also replaced deprecated ajax callback method.
bsc#1093869 follow-up
(cherry picked from commit 7ef3502fc528d7ed14a2a6a17834c0b660e96f72)
> [3.0] ui: fixed unwanted acceptance failure alert

- app/views/settings/registries/show.html.slim
- app/views/settings/registry_mirrors/show.html.slim
- app/views/settings/system_certificates/show.html.slim
it makes sense to offer the apply button directly after a user has
created a new setting
otherwise you have to navigate back to the setting index which is
not a good UX because it's hidden
in many cases a user just wants to create one setting and then
immediately apply
settings#apply-on-create
> show apply button after each setting creation

- app/views/settings/registries/show.html.slim
- app/views/settings/registry_mirrors/show.html.slim
- app/views/settings/system_certificates/show.html.slim
it makes sense to offer the apply button directly after a user has
created a new setting
otherwise you have to navigate back to the setting index which is
not a good UX because it's hidden
in many cases a user just wants to create one setting and then
immediately apply
settings#apply-on-create
(cherry picked from commit f7d227d4879e83670205a5b1b5ace65ab70afd49)
backport of https://github.com/kubic-project/velum/pull/553
> [3.0] show apply button after each setting creation

- packaging/suse/velum.spec.in
I can't see why systemd is required in velum, as it is mostly used within a container and also no unit files are provided... Probably I am missing something, but to me this dependency looks like some kind of leftover.
> Removing systemd dependency

- app/assets/javascripts/setup/openstack.js
- app/assets/javascripts/setup/setup.js
Whenever the user wants to configure openstack domain/project id/name,
they cannot fill both cases. To prevent that we are disabling the
respective opposite fields when one of the fields is filled.
bsc#1091809 ui improvement
> ux: toggle domain/project id/name inputs

- app/assets/javascripts/setup/openstack.js
- app/assets/javascripts/setup/setup.js
Whenever the user wants to configure openstack domain/project id/name,
they cannot fill both cases. To prevent that we are disabling the
respective opposite fields when one of the fields is filled.
bsc#1091809 ui improvement
(cherry picked from commit 7e6fdf10b4b6a30abe3f748af16ca18fb09153fa)
Backport of #557
> [3.0] ux: toggle domain/project id/name inputs

- app/views/setup/welcome.html.slim
This should make it more clear to the user that the value of the dashboard must be resolvable.
[Fixes bsc#1062186](https://bugzilla.suse.com/show_bug.cgi?id=1062186&GoAheadAndLogIn=1)
> Fix bsc#1062186: update tooltip to explain possible dashboard values.

- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/views/setup/welcome.html.slim
This reverts commit 99550aacb6b7c5bfa48545005039c743aa2ee853.
It turns out it's possible to use the VXLAN backend to create clusters
over segmented networks.
feature#revert-UDP-selection-UI
> Revert "Allow users to choose flannel's backend"

- app/assets/javascripts/dashboard/dashboard.js
- app/assets/stylesheets/pages/nodes_list.scss
- app/views/dashboard/index.html.slim
- spec/features/admin_node_update_feature_spec.rb
Changed update failed error message stating a generic state instead of
saying that the update failed itself.
Update admin node link only showing if `tx_update_reboot_needed` flag is
truthy. Otherwise keeps it hidden.
bsc#1082786
> ui: show proper update failed message and reboot button

- app/assets/javascripts/dashboard/dashboard.js
- app/assets/stylesheets/pages/nodes_list.scss
- app/views/dashboard/index.html.slim
- spec/features/admin_node_update_feature_spec.rb
Changed update failed error message stating a generic state instead of
saying that the update failed itself.
Update admin node link only showing if `tx_update_reboot_needed` flag is
truthy. Otherwise keeps it hidden.
bsc#1082786
(cherry picked from commit 7e70efd1cc972128c95ad420e27a5bc987e65cbd)
Backport of #565
> [3.0] ui: show proper update failed message and reboot button

- app/assets/javascripts/dashboard/dashboard.js
- spec/features/node_force_removal_feature_spec.rb
- spec/features/node_removal_feature_spec.rb
We should not consider a failed removal minion as a valid removal when
we decide to show/hide the removals link.
In this case, if we are in a scenario 1+2 and one of the workers is in
removal failed highstate, we should not show the 'Remove' link for the
other worker.
bsc#1095205
(cherry picked from commit 1137f43166f137408e76219c6e544e14b7d2510e)
Backport of #573
> [3.0] ui: do not count failed removal as minion for removal

- app/assets/javascripts/dashboard/dashboard.js
- spec/features/node_force_removal_feature_spec.rb
- spec/features/node_removal_feature_spec.rb
We should not consider a failed removal minion as a valid removal when
we decide to show/hide the removals link.
In this case, if we are in a scenario 1+2 and one of the workers is in
removal failed highstate, we should not show the 'Remove' link for the
other worker.
bsc#1095205
> ui: do not count failed removal as minion for removal

- app/views/settings/registry_mirrors/_form.html.slim
The default blank option for the registry on the mirror creation form
was confusing. To keep the same experience with the "Create new
registry" button, the solution was to simply add "Select a registry"
text to work as a placeholder.
bsc#1095255
(cherry picked from commit 7065bbcd70901f58c4235542ea67462b2bc33769)
Backport of #571
> [3.0] ui: added placeholder for mirror registry blank option

- app/views/settings/registry_mirrors/_form.html.slim
The default blank option for the registry on the mirror creation form
was confusing. To keep the same experience with the "Create new
registry" button, the solution was to simply add "Select a registry"
text to work as a placeholder.
bsc#1095255
> ui: added placeholder for mirror registry blank option

- app/models/pillar.rb
If we don't serve the flannel backend on the Pillar API, the upgrade
will use the default in the `sls` files, that is: `vxlan`.
The intent was always to keep `udp` for upgraded systems until we
migrate them to the `vxlan` backend, so make the Pillar controller
serve the current `flannel:backend` pillar value that is present
on the database (it will be `vxlan` for new installations, and `udp`
for systems coming from the 2.0 release).
Fixes: bsc#1096710
(cherry picked from commit 4d19ba2b69cd72e3853986bc6a8ba6e48b1bbcda)
> [3.0] Serve the flannel backend on the Pillar API

- app/models/pillar.rb
If we don't serve the flannel backend on the Pillar API, the upgrade
will use the default in the `sls` files, that is: `vxlan`.
The intent was always to keep `udp` for upgraded systems until we
migrate them to the `vxlan` backend, so make the Pillar controller
serve the current `flannel:backend` pillar value that is present
on the database (it will be `vxlan` for new installations, and `udp`
for systems coming from the 2.0 release).
Fixes: bsc#1096710
> Serve the flannel backend on the Pillar API

- app/assets/javascripts/dashboard/dashboard.js
- app/controllers/concerns/discovery.rb
A failed alert is shown whenever one of the nodes fails to bootstrap.
This is an optimization to only show this alert once for a specific
orchestration run. If the user closes the alert, it won't come back
unless a new orchestration happens.
bsc#1097752
> ui: don't show failed alert for repeated orchestration

- app/controllers/dashboard_controller.rb
- app/views/dashboard/autoyast.xml.erb
- lib/velum/autoyast_values.rb
- spec/controllers/dashboard_controller_spec.rb
The keyboard layout the user was using during the installation will be
used in the autoyast generated to bootstrap additional nodes.
Requires kubic-project/caasp-container-manifests#191
Signed-off-by: Florian Bergmann <fbergmann@suse.de>
> Fix bsc#1072242: Use keyboard layout from admin installation.

- packaging/suse/velum.spec.in
a simple mount through the manifests is not enough
images need to be precompiled
velum#branding
> add branding images before precompilation

- app/assets/stylesheets/components/header.scss
Logo can be both CaaSP or Kubic now and the fixed width was causing a
small misalignment with Kubic logo. Turns out that this fixed width is
not necessary at all.
fix#kubic-logo
> ui: removed fixed width for main header logo

- app/assets/javascripts/dashboard/dashboard.js
- app/models/minion.rb
- app/views/dashboard/index.html.slim
- bin/init
- db/migrate/20181708070233_add_online_status_to_minions.rb
- db/schema.rb
- packaging/suse/patches/0_set_default_salt_events_alter_time_column_value.rpm.patch
- spec/features/monitoring_feature_spec.rb
when a minion is down, it should be shown as down in the UI
> save online status through reconciler (bsc#1098436)

- app/assets/stylesheets/pages/nodes_list.scss
- app/views/dashboard/index.html.slim
On the cluster status summary we decided to rename "new" by "unassigned"
to avoid mixing terms that may confuse the user.
bsc#1100113
> ui: renamed new nodes -> unassigned nodes

- app/models/certificate.rb
- app/validators/x509_certificate_validator.rb
- spec/controllers/internal_api/v1/pillars_controller_spec.rb
- spec/controllers/settings/registries_controller_spec.rb
- spec/controllers/settings/registry_mirrors_controller_spec.rb
- spec/controllers/settings/system_certificates_controller_spec.rb
- spec/controllers/setup_controller_spec.rb
- spec/factories/certificate_factory.rb
- spec/features/settings/mirrors_feature_spec.rb
- spec/features/settings/registries_feature_spec.rb
- spec/models/certificate_spec.rb
- spec/rails_helper.rb
Fixes bsc#1097754: a certificate's text will be verified to be a `X509` certificate.
> Certificate validation

- app/controllers/internal_api/v1/pillars_controller.rb
- app/controllers/setup_controller.rb
- app/models/pillar.rb
- app/views/setup/cloud/_openstack_configuration.html.slim
- lib/tasks/cpi.rake
- spec/controllers/internal_api/v1/pillars_controller_spec.rb
Ignore OpenStack Cinder avability zone when attaching volumes.
When Nova and Cinder have different availability zones,
this should be set to true. Default is false.
> [CPI] Add option to ignore OpenStack Cinder availability zone, bsc#1095572

- app/controllers/setup_controller.rb
- app/views/dashboard/index.html.slim
- app/views/setup/worker_bootstrap.html.slim
after the bootstrap all the useful hints regarding autoyast were
not accessible anymore
bsc#1098085
> [bsc#1098085] keep information about adding nodes to the cluster

- app/assets/javascripts/setup/openstack.js
- app/assets/javascripts/setup/setup.js
- app/assets/stylesheets/components/forms.scss
- app/views/setup/cloud/_openstack_configuration.html.slim
The OpenStack API fields didn't have any additional information about
them and no indicator of which fields were required or not for a valid
configuration.
Fixes bsc#1097817
> ui: added openstack fields info and required validation

- app/controllers/setup_controller.rb
- app/views/dashboard/index.html.slim
- app/views/setup/worker_bootstrap.html.slim
after the bootstrap all the useful hints regarding autoyast were
not accessible anymore
bsc#1098085
(cherry picked from commit cd5cc077507aa8b5bd200d747503d6e351a3f403)
Backport of https://github.com/kubic-project/velum/pull/610
> [3.0][bsc#1098085] keep information about adding nodes to the cluster

- config/environments/production.rb
this fixes packaging in https://build.opensuse.org/package/show/devel:CaaSP:Head:ControllerNode/velum
also see https://github.com/rails/webpacker/issues/1285#issuecomment-367753761
> fix uglifier instantiation

- app/assets/javascripts/dashboard/dashboard.js
- app/controllers/minions_controller.rb
- app/models/minion.rb
- spec/controllers/minions_controller_spec.rb
- spec/features/node_removal_feature_spec.rb
Removing nodes is not implemented in public clouds (Azure, EC2, GCE) at this time, so the interfaces for doing so should be disabled until the feature is implemented.
> PublicCloud#remove: Not yet implemented

- config/environments/production.rb
the constant `Uglifier` is not accessible when opening a
rails console or running a rake command
fix#uglifier
https://github.com/kubic-project/velum/pull/630
@jordimassaguerpla a more elegant **nitpicky** solution would probably be to only configure `Uglifier` when we precompile the assets, as during runtime we don't really need it. But since we dont have the `PACKAGING` env anymore, we don't have an easy way to determine if we're about to precompile or not. it would look like this:
```ruby
...
if ENV["PACKAGING"]
config.assets.js_compressor = Uglifier.new(harmony: true)
end
...
```
On the other hand it might not be an issue to load `Uglifier` during the rails console session, as during runtime it seems to be loaded and accessible …
> [followup #630] require uglifier

- app/views/settings/dex_connector_ldaps/_form.html.slim
- db/migrate/20181715075510_alter_dex_defaults.rb
- db/schema.rb
- spec/features/settings/dex_connector_ldap_feature_spec.rb
- Added a database migration that removed default data from the database
- Added smart documentation on each LDAP field in place of the default data.
> Updated tool tips and removed default data

- app/models/cloud_cluster.rb
- lib/velum/salt.rb
- spec/vcr_cassettes/salt/cloud_profile.yml
- spec/vcr_cassettes/salt/login_500.yml
- spec/vcr_cassettes/salt/refresh_pillar.yml
I've added a call_runner function to salt interface and added a call to sync_pillar runner in cloud_cluster.rb. This is required to activate the external pillar, which is normally done at orchestration time, but for creating cluster nodes in the cloud, the pillar is needed before that. See also #399 for details.
I've also added a sleep(1) after the refresh_pillar, as we ran into the issue that the succeeding salt-cloud still works on the old pillar data, and this seems to work around it. I know that this is a bit ugly and perhaps can be fixed better in salt directly, but I haven't had any luck yet with narrowing the issue down.
> Fix pillar issue in public cloud

- app/controllers/updates_controller.rb
otherwise we have a window after the restart, where the reboot
admin button is still shown, as the event proccessor still needs
time to update the grains
bsc#1099015
@ereslibre i have first tried to add a `Minion.update_grains` statement to the end of `bin/init` or just before launching puma in `bin/run` but for some reason that didn't set the `tx_update_reboot_needed` flag to false after the reboot... then i came up with this solution
> [bsc#1099015] when rebooting admin, set tx_update_reboot_needed to false

- app/assets/javascripts/dashboard/dashboard.js
- app/controllers/minions_controller.rb
- app/models/minion.rb
- spec/controllers/minions_controller_spec.rb
- spec/features/node_removal_feature_spec.rb
Removing nodes is not implemented in public clouds (Azure, EC2, GCE) at this
time, so the interfaces for doing so should be disabled until the feature
is implemented.
(cherry picked from commit 377e4fe09e3ec239cfcac284e4dfef17018f95a7)
Backport of #629
> [3.0] PublicCloud#remove: Not yet implemented

- app/models/cloud_cluster.rb
- lib/velum/salt.rb
- spec/vcr_cassettes/salt/cloud_profile.yml
- spec/vcr_cassettes/salt/login_500.yml
- spec/vcr_cassettes/salt/refresh_pillar.yml
I've added a call_runner function to salt interface and added a call to sync_pillar runner in cloud_cluster.rb. This is required to activate the external pillar, which is normally done at orchestration time, but for creating cluster nodes in the cloud, the pillar is needed before that. See also https://github.com/kubic-project/velum/issues/399 for details.
I've also added a sleep(1) after the refresh_pillar, as we ran into the issue that the succeeding salt-cloud still works on the old pillar data, and this seems to work around it. I know that this is a bit ugly and perhaps can be fixed better in salt directly, but I haven't had any luck yet with narrowing the issue down.
> [3.0] Fix pillar issue in public cloud

- spec/controllers/settings/dex_connector_ldaps_controller_spec.rb
- spec/controllers/settings/registries_controller_spec.rb
- spec/controllers/settings/registry_mirrors_controller_spec.rb
- spec/controllers/settings/system_certificates_controller_spec.rb
- spec/controllers/setup_controller_spec.rb
- spec/features/settings/dex_connector_ldap_feature_spec.rb
- spec/features/settings/mirrors_feature_spec.rb
- spec/features/settings/registries_feature_spec.rb
- spec/rails_helper.rb
During #635 review we detected some flakyness while some attempts of fixing Travis. After some investigation I was able to identify an issue with the `TempFile` usage used in our `to_fixture_file` function to create temporary dynamic content fixture.
From the ruby docs:
> When a Tempfile object is garbage collected, or when the Ruby interpreter exits, its associated temporary file is automatically deleted.
In some randomized seeds a temp file was being removed and no content was being uploaded, since the file didn't exist, and the file content wasn't being displayed on the screen as expected.
Since there's no way of controlling when GC is going to remove the temp files, the only way is trying to keep the reference on hold to be usable. The solution for this was to simply return the …
> specs: fixed TempFile usage for file fixtures

- app/models/pillar.rb
Also, include PSP and DNS addons. While they won't probably be
modified, they could be used for certain use cases.
Fixes: bsc#1106193
> Allow to configure Kubernetes log level globally.

- app/assets/javascripts/settings/ldap-conn-test.js
- spec/features/settings/dex_connector_ldap_feature_spec.rb
Alter external ldap auth form to redisable save and rerequire 'check connection' when values are changed.
> Prevent changed external ldap values from skipping checks

- app/views/settings/dex_connector_ldaps/_form.html.slim
- spec/features/settings/dex_connector_ldap_feature_spec.rb
> ldap (specs): minor improvements using capybara convetions

- app/models/pillar.rb
- db/migrate/20181715075511_rename_cloud_subnet_pillar.rb
- db/schema.rb
- spec/controllers/internal_api/v1/pillars_controller_spec.rb
In v3, the subnet ID is stored in the same Pillar for all public clouds, then arranged into the appropriate pillar structure by InternalApi::V1::PillarsController#cloud_framework_contents
In v2.1, AWS had a different name for the subnet ID (for Azure & GCP, the name is consistent); therefore it is necessary to modify the pillar, if already assigned, in order to prevent losing the customer's entered data.
> [BSC#1107545] Migrate subnet pillar name v2.1 -> v3

- app/assets/javascripts/dashboard/dashboard.js
we can make use of the online status to have a more accurate status
during the update
if a node is offline during the update, it likely means that it's
rebooting
It could be misleading to see the node offline during the update. Without knowing why, it looks like sth went wrong
> use online status during update for update status

- .gitignore
- README.md
- app/assets/javascripts/dashboard/dashboard.js
- app/controllers/salt_controller.rb
- app/models/minion.rb
- app/models/salt_event.rb
- app/models/salt_handler/auth_event.rb
- app/views/dashboard/unassigned_nodes.html.slim
- app/views/setup/discovery.html.slim
- config/routes.rb
- lib/velum/salt.rb
- spec/features/bootstrap_cluster_feature_spec.rb
- spec/features/dashboard_feature_spec.rb
- spec/lib/velum/salt_spec.rb
- spec/models/minion_spec.rb
- spec/models/salt_event_spec.rb
- spec/models/salt_handler/auth_event_spec.rb
- spec/support/utils.rb
- spec/vcr_cassettes/salt/reject_minion.yml
- spec/vcr_cassettes/salt/remove_minion.yml
This adds the possibility to remove an unassigned node, from the assign_nodes page.
I also added a reject node link to the unassigned nodes, seemed to me that that functionality was missing.
*The setup step discovery can also do this.
**CATCH/HELP:** There is a time between when the remove node it's clicked and accepted and when the salt event removes that node from the DB, that the user could assign that node to a role and apply the changes, that leaves the cluster in an unstable state. If someone could help me to figure this out I would appreciate it, maybe disabling it via JS or something, don't know the correct way to approach it.
> FIX bsc#1099985 removes unassigned nodes and add a reject node link

- lib/velum/dex/ldap.rb
[bsc#1109320] Fix external auth group mapping for group attr name
Cherry-picked commit [4a672de](https://github.com/kubic-project/velum/commit/4a672de7cc6903b2682d7d2381eddf473278f857).
Link to bug:  https://bugzilla.suse.com/show_bug.cgi?id=1109320
> [3.0] [bsc#1109320] Fix external auth group mapping for group attr name

- Gemfile.lock
Backport of  https://github.com/kubic-project/velum/pull/591
(cherry picked from commit f94cdfd33a544c072cd7d924ce5cb721c212ef8a)
> [3.0] update sprockets to fix cve-2018-3760 cve#2018-3760

- app/assets/javascripts/settings/ldap-connector.js
Links browser form requirements for bindDN and password to anonymous bind status. Addresses [bsc#1109025](https://bugzilla.suse.com/show_bug.cgi?id=1109025).
> [bsc#1109025] LDAP connector can't be saved if anonymous bind

- app/controllers/updates_controller.rb
otherwise we have a window after the restart, where the reboot
admin button is still shown, as the event proccessor still needs
time to update the grains
bsc#1099015
(cherry picked from commit 34c7b11c6cfacd955701c7fefae17d7b22d6b7eb)
Backport of https://github.com/kubic-project/velum/pull/608
> [3.0] when rebooting admin, set tx_update_reboot_needed to false

- app/assets/javascripts/dashboard/dashboard.js
bsc#1108740
(cherry picked from commit c16eda7129e646fa8f9d5add02f5e78c986fff71)
backport of https://github.com/kubic-project/velum/pull/660
> [3.0][bsc#1108740] dont allow updating admin again when cluster update failed

- app/assets/javascripts/dashboard/dashboard.js
we can make use of the online status to have a more accurate status
during the update
if a node is offline during the update, it likely means that it's
rebooting
(cherry picked from commit 23bb090b5a8bd74a3f3af935701356d9aacf4276)
Backport of https://github.com/kubic-project/velum/pull/641
> [3.0][bsc#1108679] use online status during update for update status

- app/assets/stylesheets/pages/nodes_list.scss
- app/views/dashboard/index.html.slim
On the cluster status summary we decided to rename "new" by "unassigned"
to avoid mixing terms that may confuse the user.
bsc#1100113
(cherry picked from commit b18c46e19129e8c43d5e3abc87e355beae32d562)
Backport of #604
> [3.0] ui: renamed new nodes -> unassigned nodes

- app/controllers/dashboard_controller.rb
- app/views/dashboard/autoyast.xml.erb
- lib/velum/autoyast_values.rb
- spec/controllers/dashboard_controller_spec.rb
The keyboard layout the user was using during the installation will be
used in the autoyast generated to bootstrap additional nodes.
Requires kubic-project/caasp-container-manifests#195
Backport of https://github.com/kubic-project/velum/pull/575
> [3.0] Fix bsc#1072242: Use keyboard layout from admin installation.

- app/models/minion.rb
Fixes: bsc#1103307
(cherry picked from commit a9e64beb5918c8432daeaee533731fc9789542de)
Backport of https://github.com/kubic-project/velum/pull/614
> [3.0] Update the minion hostname in a regular basis, based on the grain information.

- app/views/oidc/done.html.slim
This fixes issue #612 
github-issue#612
Backport of https://github.com/kubic-project/velum/pull/624#pullrequestreview-145154356
Signed-off-by: Flavio Castelli <fcastelli@suse.com>
(cherry picked from commit 0b93b79ee3099647027e5ba3c678ca1289c4c38b)
> Fix smally typo

- config/initializers/filter_parameter_logging.rb
Velum uses pass, password, and bind_pw symbols accordingly.
Diverse symbols in velum are exposed in Velum logs. 
After symbols were added in log filters, logs in admin:/var/log/containers  will shows:
{"log":"Processing by SetupController#configure as HTML\n","stream":"stdout","time":"2018-10-18T00:37:42.923336515Z"}
{"log":"  Parameters: {\"utf8\"=\u003e\"✓\", \"authenticity_token\"=\u003e\"[FILTERED]\", \"settings\"=\u003e{\"dashboard\"=\u003e\"10.17.1.0\", \"tiller\"=\u003e\"false\", \"cluster_cidr\"=\u003e\"172.16.0.0/13\", \"cluster_cidr_min\"=\u003e\"172.16.0.0\", \"cluster_cidr_max\"=\u003e\"172.23.255.255\", \"cluster_cidr_len\"=\u003e\"23\", \"services_cidr\"=\u003e\"172.24.0.0/16\", \"api_cluster_ip\"=\u003e\"172.24.0.1\", \"dns_cluster_ip\"=\u003e\"172.24.0.2\", …
> Velum: Add more log filters for user's secrets, pass, and tokens

- app/models/cloud_cluster.rb
Fix for current_cluster_size. Current implementation always returns 0, so the "add node" page in the cloud does not work properly.
> cloud_cluster: fix current_cluster_size (bsc#1113316)

- app/assets/javascripts/dashboard/dashboard.js
we need to check the admin for `tx_update_reboot_needed`, not the
minions
https://github.com/kubic-project/velum/pull/670
> followup fix for bsc#1108740

- app/controllers/internal_api/v1/pillars_controller.rb
- app/controllers/settings/dex_connector_oidcs_controller.rb
- app/helpers/settings_helper.rb
- app/models/dex_connector_oidc.rb
- app/validators/http_url_validator.rb
- app/validators/oidc_provider_validator.rb
- app/views/settings/_sidebar.html.slim
- app/views/settings/dex_connector_oidcs/_form.html.slim
- app/views/settings/dex_connector_oidcs/edit.html.slim
- app/views/settings/dex_connector_oidcs/index.html.slim
- app/views/settings/dex_connector_oidcs/new.html.slim
- app/views/settings/dex_connector_oidcs/show.html.slim
- config/initializers/filter_parameter_logging.rb
- config/routes.rb
- db/migrate/20182106194300_create_dex_connectors_oidc.rb
- db/schema.rb
- docs/oidc_testing/README.md
- docs/oidc_testing/docker-compose.yml
- docs/oidc_testing/examples/.gitignore
- docs/oidc_testing/examples/config-dev.yaml.example
- lib/velum/dex/oidc.rb
- spec/controllers/internal_api/v1/pillars_controller_spec.rb
- spec/controllers/settings/dex_connector_oidcs_controller_spec.rb
- spec/factories/dex_connectors_oidc_factory.rb
- spec/features/settings/dex_connector_oidc_feature_spec.rb
- spec/models/dex_connector_oidc_spec.rb
- spec/spec_helper.rb
- spec/support/database_cleaner.rb
- spec/vcr_cassettes/oidc/invalid_connector.yml
- spec/vcr_cassettes/oidc/validate_connector.yml
This set of changes implements external OIDC connector support within Velum.  It's based upon the LDAP connector, and should incorporate the majority of the relevant lessons learned from that implementation.
> OIDC Connector support

- app/controllers/internal_api/v1/pillars_controller.rb
- app/controllers/setup_controller.rb
- app/models/cloud_cluster.rb
- app/views/setup/worker_bootstrap_azure.html.slim
- spec/controllers/internal_api/v1/pillars_controller_spec.rb
- spec/controllers/setup_controller_spec.rb
- spec/models/cloud_cluster_spec.rb
Supplying credentials is no longer required for starting instances in Azure; Azure MSI acts like machine accounts in AWS IAM, for example, where the instance is granted permission to interact with the framework (for starting cluster instances, in our case).
> [BSC#1101219] Use MSI authorization in Azure

- lib/tasks/cpi.rake
(cherry picked from commit f1c98989736e08ba24e9258356d5ef7a58764f20)
> [3.0] Fix correct pillar names for CPI rake task (bsc#1111361)

- bin/init
(cherry picked from commit a17a674e6e6d8b54d2b103a5b1d5d730192f7319)
> [3.0] [CPI] OpenStack Cloud Provider config file doesn't exist (bsc#1111361)

- lib/velum/salt.rb
- spec/lib/velum/salt_spec.rb
- spec/vcr_cassettes/salt/reject_minion.yml
- spec/vcr_cassettes/salt/remove_minion.yml
Backport of #699 
(cherry picked from commit c74170568dfc26e31e75814a0520e0e6fb3865ae)
> [3.0] Fix bsc#1117152: Do not parse the return code but the JSON response.

- config/environments/production.rb
the constant `Uglifier` is not accessible when opening a
rails console or running a rake command
fix#uglifier
(cherry picked from commit 68e42c9d9bf3d589b8ffede158ed51e5f2149664)
bsc#1118907
#630 #632 
`Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).`
> [3.0][bsc#1118907] require uglifier only during packaging

- .travis.yml
The `gem update --system` hack got fixed. this Pr should stabilze more build travis.
See https://github.com/travis-ci/travis-ci/issues/8978
and https://github.com/plataformatec/devise/commit/8e49661fd167eed7a97281aa09aea7bc6bfd1bf5
Travis ruby-head fails but i think it failed also before. I'm not familiar with that. HTH! :rocket:
> remove hack, not anymore needed 

- .travis.yml
this is a backport from https://github.com/kubic-project/velum/pull/709
Don't run gem update --system
Related to `gem update --system`:
- travis-ci/travis-ci#8978
- rubygems/rubygems#2123
> Remove gem-install workaround

- app/controllers/settings/external_cert_controller.rb
- app/views/settings/external_cert/_form.html.slim
- app/views/settings/external_cert/index.html.slim
- config/ext_cert_minion.yaml
- config/ext_cert_pillar.yaml
- spec/features/settings/external_cert_feature_spec.rb
Added logic for checking of a certificates's SubjectAltNames against list of required hostnames for Velum, KubeAPI and Dex.
> External certs hostname check

- app/controllers/settings/external_cert_controller.rb
Added nocov to the two places in code that don't need to be tested. They are code for IPv6 ( forward looking but not used ) and handling to prevent error in exceptional case ( which I don't know how to trigger and isn't important )
> Add nocov on things we are intentionally not covering

- app/views/setup/cloud/_openstack_configuration.html.slim
This change is reverting ignore_vol_az option back to Velum CPI.
> [3.0][CPI] Fix regression and re-add option to CPI, bsc#1122439

- app/models/system_certificate.rb
- app/validators/system_certificate_name_validator.rb
- spec/models/system_certificate_spec.rb
This way when salt extracts the name to construct the certificate path,
it will not be able to break out of the folder for trusted certificates.
This is a first layer fix for bnc#1121147.
> [bsc#1121147] Do not allow '.' or '/' symbols in system certificate names.
